// Code generated by ent, DO NOT EDIT.

package voucherorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the voucherorder type in the database.
	Label = "voucher_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldKvProductID holds the string denoting the kv_product_id field in the database.
	FieldKvProductID = "kv_product_id"
	// FieldProductName holds the string denoting the product_name field in the database.
	FieldProductName = "product_name"
	// FieldDenomination holds the string denoting the denomination field in the database.
	FieldDenomination = "denomination"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldSubtotal holds the string denoting the subtotal field in the database.
	FieldSubtotal = "subtotal"
	// FieldFeeAmount holds the string denoting the fee_amount field in the database.
	FieldFeeAmount = "fee_amount"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldPaymentRef holds the string denoting the payment_ref field in the database.
	FieldPaymentRef = "payment_ref"
	// FieldPaymentProofPath holds the string denoting the payment_proof_path field in the database.
	FieldPaymentProofPath = "payment_proof_path"
	// FieldBankAccountID holds the string denoting the bank_account_id field in the database.
	FieldBankAccountID = "bank_account_id"
	// FieldKvRetrieveReference holds the string denoting the kv_retrieve_reference field in the database.
	FieldKvRetrieveReference = "kv_retrieve_reference"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldRejectReason holds the string denoting the reject_reason field in the database.
	FieldRejectReason = "reject_reason"
	// FieldFulfillError holds the string denoting the fulfill_error field in the database.
	FieldFulfillError = "fulfill_error"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldVerifiedAt holds the string denoting the verified_at field in the database.
	FieldVerifiedAt = "verified_at"
	// FieldFulfilledAt holds the string denoting the fulfilled_at field in the database.
	FieldFulfilledAt = "fulfilled_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldClientIP holds the string denoting the client_ip field in the database.
	FieldClientIP = "client_ip"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the voucherorder in the database.
	Table = "voucher_orders"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "voucher_orders"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for voucherorder fields.
var Columns = []string{
	FieldID,
	FieldOrderNo,
	FieldUserID,
	FieldUserEmail,
	FieldUserName,
	FieldStatus,
	FieldProductID,
	FieldKvProductID,
	FieldProductName,
	FieldDenomination,
	FieldQuantity,
	FieldUnitPrice,
	FieldSubtotal,
	FieldFeeAmount,
	FieldTotalAmount,
	FieldCurrency,
	FieldPaymentRef,
	FieldPaymentProofPath,
	FieldBankAccountID,
	FieldKvRetrieveReference,
	FieldIdempotencyKey,
	FieldRejectReason,
	FieldFulfillError,
	FieldExpiresAt,
	FieldVerifiedAt,
	FieldFulfilledAt,
	FieldCompletedAt,
	FieldClientIP,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	OrderNoValidator func(string) error
	// UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	UserEmailValidator func(string) error
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// ProductNameValidator is a validator for the "product_name" field. It is called by the builders before save.
	ProductNameValidator func(string) error
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity int
	// DefaultFeeAmount holds the default value on creation for the "fee_amount" field.
	DefaultFeeAmount float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// PaymentRefValidator is a validator for the "payment_ref" field. It is called by the builders before save.
	PaymentRefValidator func(string) error
	// PaymentProofPathValidator is a validator for the "payment_proof_path" field. It is called by the builders before save.
	PaymentProofPathValidator func(string) error
	// KvRetrieveReferenceValidator is a validator for the "kv_retrieve_reference" field. It is called by the builders before save.
	KvRetrieveReferenceValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// DefaultClientIP holds the default value on creation for the "client_ip" field.
	DefaultClientIP string
	// ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	ClientIPValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the VoucherOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserEmail orders the results by the user_email field.
func ByUserEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserEmail, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByKvProductID orders the results by the kv_product_id field.
func ByKvProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKvProductID, opts...).ToFunc()
}

// ByProductName orders the results by the product_name field.
func ByProductName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductName, opts...).ToFunc()
}

// ByDenomination orders the results by the denomination field.
func ByDenomination(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDenomination, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// BySubtotal orders the results by the subtotal field.
func BySubtotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubtotal, opts...).ToFunc()
}

// ByFeeAmount orders the results by the fee_amount field.
func ByFeeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeAmount, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByPaymentRef orders the results by the payment_ref field.
func ByPaymentRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentRef, opts...).ToFunc()
}

// ByPaymentProofPath orders the results by the payment_proof_path field.
func ByPaymentProofPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentProofPath, opts...).ToFunc()
}

// ByBankAccountID orders the results by the bank_account_id field.
func ByBankAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankAccountID, opts...).ToFunc()
}

// ByKvRetrieveReference orders the results by the kv_retrieve_reference field.
func ByKvRetrieveReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKvRetrieveReference, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByRejectReason orders the results by the reject_reason field.
func ByRejectReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectReason, opts...).ToFunc()
}

// ByFulfillError orders the results by the fulfill_error field.
func ByFulfillError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFulfillError, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByVerifiedAt orders the results by the verified_at field.
func ByVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifiedAt, opts...).ToFunc()
}

// ByFulfilledAt orders the results by the fulfilled_at field.
func ByFulfilledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFulfilledAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByClientIP orders the results by the client_ip field.
func ByClientIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientIP, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
