// Code generated by ent, DO NOT EDIT.

package catalogmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the catalogmodel type in the database.
	Label = "catalog_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldVendor holds the string denoting the vendor field in the database.
	FieldVendor = "vendor"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldDocURL holds the string denoting the doc_url field in the database.
	FieldDocURL = "doc_url"
	// FieldIconURL holds the string denoting the icon_url field in the database.
	FieldIconURL = "icon_url"
	// FieldContextWindow holds the string denoting the context_window field in the database.
	FieldContextWindow = "context_window"
	// FieldMaxOutputTokens holds the string denoting the max_output_tokens field in the database.
	FieldMaxOutputTokens = "max_output_tokens"
	// FieldInputModalities holds the string denoting the input_modalities field in the database.
	FieldInputModalities = "input_modalities"
	// FieldOutputModalities holds the string denoting the output_modalities field in the database.
	FieldOutputModalities = "output_modalities"
	// FieldFeatures holds the string denoting the features field in the database.
	FieldFeatures = "features"
	// FieldInputPrice holds the string denoting the input_price field in the database.
	FieldInputPrice = "input_price"
	// FieldOutputPrice holds the string denoting the output_price field in the database.
	FieldOutputPrice = "output_price"
	// FieldCacheWritePrice holds the string denoting the cache_write_price field in the database.
	FieldCacheWritePrice = "cache_write_price"
	// FieldCacheReadPrice holds the string denoting the cache_read_price field in the database.
	FieldCacheReadPrice = "cache_read_price"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldIsEnabled holds the string denoting the is_enabled field in the database.
	FieldIsEnabled = "is_enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the catalogmodel in the database.
	Table = "catalog_models"
)

// Columns holds all SQL columns for catalogmodel fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldName,
	FieldVendor,
	FieldCategory,
	FieldDescription,
	FieldTags,
	FieldDocURL,
	FieldIconURL,
	FieldContextWindow,
	FieldMaxOutputTokens,
	FieldInputModalities,
	FieldOutputModalities,
	FieldFeatures,
	FieldInputPrice,
	FieldOutputPrice,
	FieldCacheWritePrice,
	FieldCacheReadPrice,
	FieldCurrency,
	FieldIsEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	ModelIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultVendor holds the default value on creation for the "vendor" field.
	DefaultVendor string
	// VendorValidator is a validator for the "vendor" field. It is called by the builders before save.
	VendorValidator func(string) error
	// DefaultCategory holds the default value on creation for the "category" field.
	DefaultCategory string
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultDocURL holds the default value on creation for the "doc_url" field.
	DefaultDocURL string
	// DefaultIconURL holds the default value on creation for the "icon_url" field.
	DefaultIconURL string
	// DefaultContextWindow holds the default value on creation for the "context_window" field.
	DefaultContextWindow int64
	// DefaultMaxOutputTokens holds the default value on creation for the "max_output_tokens" field.
	DefaultMaxOutputTokens int64
	// DefaultInputPrice holds the default value on creation for the "input_price" field.
	DefaultInputPrice float64
	// DefaultOutputPrice holds the default value on creation for the "output_price" field.
	DefaultOutputPrice float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultIsEnabled holds the default value on creation for the "is_enabled" field.
	DefaultIsEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CatalogModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByVendor orders the results by the vendor field.
func ByVendor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVendor, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByDocURL orders the results by the doc_url field.
func ByDocURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocURL, opts...).ToFunc()
}

// ByIconURL orders the results by the icon_url field.
func ByIconURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIconURL, opts...).ToFunc()
}

// ByContextWindow orders the results by the context_window field.
func ByContextWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextWindow, opts...).ToFunc()
}

// ByMaxOutputTokens orders the results by the max_output_tokens field.
func ByMaxOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxOutputTokens, opts...).ToFunc()
}

// ByInputPrice orders the results by the input_price field.
func ByInputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputPrice, opts...).ToFunc()
}

// ByOutputPrice orders the results by the output_price field.
func ByOutputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputPrice, opts...).ToFunc()
}

// ByCacheWritePrice orders the results by the cache_write_price field.
func ByCacheWritePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWritePrice, opts...).ToFunc()
}

// ByCacheReadPrice orders the results by the cache_read_price field.
func ByCacheReadPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadPrice, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByIsEnabled orders the results by the is_enabled field.
func ByIsEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
