// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/catalogmodel"
)

// CatalogModelCreate is the builder for creating a CatalogModel entity.
type CatalogModelCreate struct {
	config
	mutation *CatalogModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModelID sets the "model_id" field.
func (_c *CatalogModelCreate) SetModelID(v string) *CatalogModelCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CatalogModelCreate) SetName(v string) *CatalogModelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetVendor sets the "vendor" field.
func (_c *CatalogModelCreate) SetVendor(v string) *CatalogModelCreate {
	_c.mutation.SetVendor(v)
	return _c
}

// SetNillableVendor sets the "vendor" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableVendor(v *string) *CatalogModelCreate {
	if v != nil {
		_c.SetVendor(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *CatalogModelCreate) SetCategory(v string) *CatalogModelCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableCategory(v *string) *CatalogModelCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *CatalogModelCreate) SetDescription(v string) *CatalogModelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableDescription(v *string) *CatalogModelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *CatalogModelCreate) SetTags(v []string) *CatalogModelCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetDocURL sets the "doc_url" field.
func (_c *CatalogModelCreate) SetDocURL(v string) *CatalogModelCreate {
	_c.mutation.SetDocURL(v)
	return _c
}

// SetNillableDocURL sets the "doc_url" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableDocURL(v *string) *CatalogModelCreate {
	if v != nil {
		_c.SetDocURL(*v)
	}
	return _c
}

// SetIconURL sets the "icon_url" field.
func (_c *CatalogModelCreate) SetIconURL(v string) *CatalogModelCreate {
	_c.mutation.SetIconURL(v)
	return _c
}

// SetNillableIconURL sets the "icon_url" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableIconURL(v *string) *CatalogModelCreate {
	if v != nil {
		_c.SetIconURL(*v)
	}
	return _c
}

// SetContextWindow sets the "context_window" field.
func (_c *CatalogModelCreate) SetContextWindow(v int64) *CatalogModelCreate {
	_c.mutation.SetContextWindow(v)
	return _c
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableContextWindow(v *int64) *CatalogModelCreate {
	if v != nil {
		_c.SetContextWindow(*v)
	}
	return _c
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_c *CatalogModelCreate) SetMaxOutputTokens(v int64) *CatalogModelCreate {
	_c.mutation.SetMaxOutputTokens(v)
	return _c
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableMaxOutputTokens(v *int64) *CatalogModelCreate {
	if v != nil {
		_c.SetMaxOutputTokens(*v)
	}
	return _c
}

// SetInputModalities sets the "input_modalities" field.
func (_c *CatalogModelCreate) SetInputModalities(v []string) *CatalogModelCreate {
	_c.mutation.SetInputModalities(v)
	return _c
}

// SetOutputModalities sets the "output_modalities" field.
func (_c *CatalogModelCreate) SetOutputModalities(v []string) *CatalogModelCreate {
	_c.mutation.SetOutputModalities(v)
	return _c
}

// SetFeatures sets the "features" field.
func (_c *CatalogModelCreate) SetFeatures(v []string) *CatalogModelCreate {
	_c.mutation.SetFeatures(v)
	return _c
}

// SetInputPrice sets the "input_price" field.
func (_c *CatalogModelCreate) SetInputPrice(v float64) *CatalogModelCreate {
	_c.mutation.SetInputPrice(v)
	return _c
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableInputPrice(v *float64) *CatalogModelCreate {
	if v != nil {
		_c.SetInputPrice(*v)
	}
	return _c
}

// SetOutputPrice sets the "output_price" field.
func (_c *CatalogModelCreate) SetOutputPrice(v float64) *CatalogModelCreate {
	_c.mutation.SetOutputPrice(v)
	return _c
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableOutputPrice(v *float64) *CatalogModelCreate {
	if v != nil {
		_c.SetOutputPrice(*v)
	}
	return _c
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_c *CatalogModelCreate) SetCacheWritePrice(v float64) *CatalogModelCreate {
	_c.mutation.SetCacheWritePrice(v)
	return _c
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableCacheWritePrice(v *float64) *CatalogModelCreate {
	if v != nil {
		_c.SetCacheWritePrice(*v)
	}
	return _c
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_c *CatalogModelCreate) SetCacheReadPrice(v float64) *CatalogModelCreate {
	_c.mutation.SetCacheReadPrice(v)
	return _c
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableCacheReadPrice(v *float64) *CatalogModelCreate {
	if v != nil {
		_c.SetCacheReadPrice(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *CatalogModelCreate) SetCurrency(v string) *CatalogModelCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableCurrency(v *string) *CatalogModelCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *CatalogModelCreate) SetIsEnabled(v bool) *CatalogModelCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableIsEnabled(v *bool) *CatalogModelCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CatalogModelCreate) SetCreatedAt(v time.Time) *CatalogModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableCreatedAt(v *time.Time) *CatalogModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CatalogModelCreate) SetUpdatedAt(v time.Time) *CatalogModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CatalogModelCreate) SetNillableUpdatedAt(v *time.Time) *CatalogModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CatalogModelMutation object of the builder.
func (_c *CatalogModelCreate) Mutation() *CatalogModelMutation {
	return _c.mutation
}

// Save creates the CatalogModel in the database.
func (_c *CatalogModelCreate) Save(ctx context.Context) (*CatalogModel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CatalogModelCreate) SaveX(ctx context.Context) *CatalogModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CatalogModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CatalogModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CatalogModelCreate) defaults() {
	if _, ok := _c.mutation.Vendor(); !ok {
		v := catalogmodel.DefaultVendor
		_c.mutation.SetVendor(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := catalogmodel.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := catalogmodel.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.DocURL(); !ok {
		v := catalogmodel.DefaultDocURL
		_c.mutation.SetDocURL(v)
	}
	if _, ok := _c.mutation.IconURL(); !ok {
		v := catalogmodel.DefaultIconURL
		_c.mutation.SetIconURL(v)
	}
	if _, ok := _c.mutation.ContextWindow(); !ok {
		v := catalogmodel.DefaultContextWindow
		_c.mutation.SetContextWindow(v)
	}
	if _, ok := _c.mutation.MaxOutputTokens(); !ok {
		v := catalogmodel.DefaultMaxOutputTokens
		_c.mutation.SetMaxOutputTokens(v)
	}
	if _, ok := _c.mutation.InputPrice(); !ok {
		v := catalogmodel.DefaultInputPrice
		_c.mutation.SetInputPrice(v)
	}
	if _, ok := _c.mutation.OutputPrice(); !ok {
		v := catalogmodel.DefaultOutputPrice
		_c.mutation.SetOutputPrice(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := catalogmodel.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := catalogmodel.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := catalogmodel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := catalogmodel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CatalogModelCreate) check() error {
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "CatalogModel.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := catalogmodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "CatalogModel.model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CatalogModel.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := catalogmodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CatalogModel.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Vendor(); !ok {
		return &ValidationError{Name: "vendor", err: errors.New(`ent: missing required field "CatalogModel.vendor"`)}
	}
	if v, ok := _c.mutation.Vendor(); ok {
		if err := catalogmodel.VendorValidator(v); err != nil {
			return &ValidationError{Name: "vendor", err: fmt.Errorf(`ent: validator failed for field "CatalogModel.vendor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "CatalogModel.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := catalogmodel.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "CatalogModel.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "CatalogModel.description"`)}
	}
	if _, ok := _c.mutation.DocURL(); !ok {
		return &ValidationError{Name: "doc_url", err: errors.New(`ent: missing required field "CatalogModel.doc_url"`)}
	}
	if _, ok := _c.mutation.IconURL(); !ok {
		return &ValidationError{Name: "icon_url", err: errors.New(`ent: missing required field "CatalogModel.icon_url"`)}
	}
	if _, ok := _c.mutation.ContextWindow(); !ok {
		return &ValidationError{Name: "context_window", err: errors.New(`ent: missing required field "CatalogModel.context_window"`)}
	}
	if _, ok := _c.mutation.MaxOutputTokens(); !ok {
		return &ValidationError{Name: "max_output_tokens", err: errors.New(`ent: missing required field "CatalogModel.max_output_tokens"`)}
	}
	if _, ok := _c.mutation.InputPrice(); !ok {
		return &ValidationError{Name: "input_price", err: errors.New(`ent: missing required field "CatalogModel.input_price"`)}
	}
	if _, ok := _c.mutation.OutputPrice(); !ok {
		return &ValidationError{Name: "output_price", err: errors.New(`ent: missing required field "CatalogModel.output_price"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "CatalogModel.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := catalogmodel.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CatalogModel.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		return &ValidationError{Name: "is_enabled", err: errors.New(`ent: missing required field "CatalogModel.is_enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CatalogModel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CatalogModel.updated_at"`)}
	}
	return nil
}

func (_c *CatalogModelCreate) sqlSave(ctx context.Context) (*CatalogModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CatalogModelCreate) createSpec() (*CatalogModel, *sqlgraph.CreateSpec) {
	var (
		_node = &CatalogModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(catalogmodel.Table, sqlgraph.NewFieldSpec(catalogmodel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(catalogmodel.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(catalogmodel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Vendor(); ok {
		_spec.SetField(catalogmodel.FieldVendor, field.TypeString, value)
		_node.Vendor = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(catalogmodel.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(catalogmodel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(catalogmodel.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.DocURL(); ok {
		_spec.SetField(catalogmodel.FieldDocURL, field.TypeString, value)
		_node.DocURL = value
	}
	if value, ok := _c.mutation.IconURL(); ok {
		_spec.SetField(catalogmodel.FieldIconURL, field.TypeString, value)
		_node.IconURL = value
	}
	if value, ok := _c.mutation.ContextWindow(); ok {
		_spec.SetField(catalogmodel.FieldContextWindow, field.TypeInt64, value)
		_node.ContextWindow = value
	}
	if value, ok := _c.mutation.MaxOutputTokens(); ok {
		_spec.SetField(catalogmodel.FieldMaxOutputTokens, field.TypeInt64, value)
		_node.MaxOutputTokens = value
	}
	if value, ok := _c.mutation.InputModalities(); ok {
		_spec.SetField(catalogmodel.FieldInputModalities, field.TypeJSON, value)
		_node.InputModalities = value
	}
	if value, ok := _c.mutation.OutputModalities(); ok {
		_spec.SetField(catalogmodel.FieldOutputModalities, field.TypeJSON, value)
		_node.OutputModalities = value
	}
	if value, ok := _c.mutation.Features(); ok {
		_spec.SetField(catalogmodel.FieldFeatures, field.TypeJSON, value)
		_node.Features = value
	}
	if value, ok := _c.mutation.InputPrice(); ok {
		_spec.SetField(catalogmodel.FieldInputPrice, field.TypeFloat64, value)
		_node.InputPrice = value
	}
	if value, ok := _c.mutation.OutputPrice(); ok {
		_spec.SetField(catalogmodel.FieldOutputPrice, field.TypeFloat64, value)
		_node.OutputPrice = value
	}
	if value, ok := _c.mutation.CacheWritePrice(); ok {
		_spec.SetField(catalogmodel.FieldCacheWritePrice, field.TypeFloat64, value)
		_node.CacheWritePrice = &value
	}
	if value, ok := _c.mutation.CacheReadPrice(); ok {
		_spec.SetField(catalogmodel.FieldCacheReadPrice, field.TypeFloat64, value)
		_node.CacheReadPrice = &value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(catalogmodel.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(catalogmodel.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(catalogmodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(catalogmodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CatalogModel.Create().
//		SetModelID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CatalogModelUpsert) {
//			SetModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *CatalogModelCreate) OnConflict(opts ...sql.ConflictOption) *CatalogModelUpsertOne {
	_c.conflict = opts
	return &CatalogModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CatalogModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CatalogModelCreate) OnConflictColumns(columns ...string) *CatalogModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CatalogModelUpsertOne{
		create: _c,
	}
}

type (
	// CatalogModelUpsertOne is the builder for "upsert"-ing
	//  one CatalogModel node.
	CatalogModelUpsertOne struct {
		create *CatalogModelCreate
	}

	// CatalogModelUpsert is the "OnConflict" setter.
	CatalogModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetModelID sets the "model_id" field.
func (u *CatalogModelUpsert) SetModelID(v string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateModelID() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldModelID)
	return u
}

// SetName sets the "name" field.
func (u *CatalogModelUpsert) SetName(v string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateName() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldName)
	return u
}

// SetVendor sets the "vendor" field.
func (u *CatalogModelUpsert) SetVendor(v string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldVendor, v)
	return u
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateVendor() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldVendor)
	return u
}

// SetCategory sets the "category" field.
func (u *CatalogModelUpsert) SetCategory(v string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateCategory() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldCategory)
	return u
}

// SetDescription sets the "description" field.
func (u *CatalogModelUpsert) SetDescription(v string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateDescription() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldDescription)
	return u
}

// SetTags sets the "tags" field.
func (u *CatalogModelUpsert) SetTags(v []string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateTags() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *CatalogModelUpsert) ClearTags() *CatalogModelUpsert {
	u.SetNull(catalogmodel.FieldTags)
	return u
}

// SetDocURL sets the "doc_url" field.
func (u *CatalogModelUpsert) SetDocURL(v string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldDocURL, v)
	return u
}

// UpdateDocURL sets the "doc_url" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateDocURL() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldDocURL)
	return u
}

// SetIconURL sets the "icon_url" field.
func (u *CatalogModelUpsert) SetIconURL(v string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldIconURL, v)
	return u
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateIconURL() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldIconURL)
	return u
}

// SetContextWindow sets the "context_window" field.
func (u *CatalogModelUpsert) SetContextWindow(v int64) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldContextWindow, v)
	return u
}

// UpdateContextWindow sets the "context_window" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateContextWindow() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldContextWindow)
	return u
}

// AddContextWindow adds v to the "context_window" field.
func (u *CatalogModelUpsert) AddContextWindow(v int64) *CatalogModelUpsert {
	u.Add(catalogmodel.FieldContextWindow, v)
	return u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (u *CatalogModelUpsert) SetMaxOutputTokens(v int64) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldMaxOutputTokens, v)
	return u
}

// UpdateMaxOutputTokens sets the "max_output_tokens" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateMaxOutputTokens() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldMaxOutputTokens)
	return u
}

// AddMaxOutputTokens adds v to the "max_output_tokens" field.
func (u *CatalogModelUpsert) AddMaxOutputTokens(v int64) *CatalogModelUpsert {
	u.Add(catalogmodel.FieldMaxOutputTokens, v)
	return u
}

// SetInputModalities sets the "input_modalities" field.
func (u *CatalogModelUpsert) SetInputModalities(v []string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldInputModalities, v)
	return u
}

// UpdateInputModalities sets the "input_modalities" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateInputModalities() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldInputModalities)
	return u
}

// ClearInputModalities clears the value of the "input_modalities" field.
func (u *CatalogModelUpsert) ClearInputModalities() *CatalogModelUpsert {
	u.SetNull(catalogmodel.FieldInputModalities)
	return u
}

// SetOutputModalities sets the "output_modalities" field.
func (u *CatalogModelUpsert) SetOutputModalities(v []string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldOutputModalities, v)
	return u
}

// UpdateOutputModalities sets the "output_modalities" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateOutputModalities() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldOutputModalities)
	return u
}

// ClearOutputModalities clears the value of the "output_modalities" field.
func (u *CatalogModelUpsert) ClearOutputModalities() *CatalogModelUpsert {
	u.SetNull(catalogmodel.FieldOutputModalities)
	return u
}

// SetFeatures sets the "features" field.
func (u *CatalogModelUpsert) SetFeatures(v []string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldFeatures, v)
	return u
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateFeatures() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldFeatures)
	return u
}

// ClearFeatures clears the value of the "features" field.
func (u *CatalogModelUpsert) ClearFeatures() *CatalogModelUpsert {
	u.SetNull(catalogmodel.FieldFeatures)
	return u
}

// SetInputPrice sets the "input_price" field.
func (u *CatalogModelUpsert) SetInputPrice(v float64) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldInputPrice, v)
	return u
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateInputPrice() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldInputPrice)
	return u
}

// AddInputPrice adds v to the "input_price" field.
func (u *CatalogModelUpsert) AddInputPrice(v float64) *CatalogModelUpsert {
	u.Add(catalogmodel.FieldInputPrice, v)
	return u
}

// SetOutputPrice sets the "output_price" field.
func (u *CatalogModelUpsert) SetOutputPrice(v float64) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldOutputPrice, v)
	return u
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateOutputPrice() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldOutputPrice)
	return u
}

// AddOutputPrice adds v to the "output_price" field.
func (u *CatalogModelUpsert) AddOutputPrice(v float64) *CatalogModelUpsert {
	u.Add(catalogmodel.FieldOutputPrice, v)
	return u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *CatalogModelUpsert) SetCacheWritePrice(v float64) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldCacheWritePrice, v)
	return u
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateCacheWritePrice() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldCacheWritePrice)
	return u
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *CatalogModelUpsert) AddCacheWritePrice(v float64) *CatalogModelUpsert {
	u.Add(catalogmodel.FieldCacheWritePrice, v)
	return u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *CatalogModelUpsert) ClearCacheWritePrice() *CatalogModelUpsert {
	u.SetNull(catalogmodel.FieldCacheWritePrice)
	return u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *CatalogModelUpsert) SetCacheReadPrice(v float64) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldCacheReadPrice, v)
	return u
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateCacheReadPrice() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldCacheReadPrice)
	return u
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *CatalogModelUpsert) AddCacheReadPrice(v float64) *CatalogModelUpsert {
	u.Add(catalogmodel.FieldCacheReadPrice, v)
	return u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *CatalogModelUpsert) ClearCacheReadPrice() *CatalogModelUpsert {
	u.SetNull(catalogmodel.FieldCacheReadPrice)
	return u
}

// SetCurrency sets the "currency" field.
func (u *CatalogModelUpsert) SetCurrency(v string) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateCurrency() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldCurrency)
	return u
}

// SetIsEnabled sets the "is_enabled" field.
func (u *CatalogModelUpsert) SetIsEnabled(v bool) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldIsEnabled, v)
	return u
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateIsEnabled() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldIsEnabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CatalogModelUpsert) SetUpdatedAt(v time.Time) *CatalogModelUpsert {
	u.Set(catalogmodel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CatalogModelUpsert) UpdateUpdatedAt() *CatalogModelUpsert {
	u.SetExcluded(catalogmodel.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CatalogModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CatalogModelUpsertOne) UpdateNewValues() *CatalogModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(catalogmodel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CatalogModel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CatalogModelUpsertOne) Ignore() *CatalogModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CatalogModelUpsertOne) DoNothing() *CatalogModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CatalogModelCreate.OnConflict
// documentation for more info.
func (u *CatalogModelUpsertOne) Update(set func(*CatalogModelUpsert)) *CatalogModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CatalogModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelID sets the "model_id" field.
func (u *CatalogModelUpsertOne) SetModelID(v string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateModelID() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateModelID()
	})
}

// SetName sets the "name" field.
func (u *CatalogModelUpsertOne) SetName(v string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateName() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateName()
	})
}

// SetVendor sets the "vendor" field.
func (u *CatalogModelUpsertOne) SetVendor(v string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetVendor(v)
	})
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateVendor() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateVendor()
	})
}

// SetCategory sets the "category" field.
func (u *CatalogModelUpsertOne) SetCategory(v string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateCategory() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateCategory()
	})
}

// SetDescription sets the "description" field.
func (u *CatalogModelUpsertOne) SetDescription(v string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateDescription() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateDescription()
	})
}

// SetTags sets the "tags" field.
func (u *CatalogModelUpsertOne) SetTags(v []string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateTags() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *CatalogModelUpsertOne) ClearTags() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearTags()
	})
}

// SetDocURL sets the "doc_url" field.
func (u *CatalogModelUpsertOne) SetDocURL(v string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetDocURL(v)
	})
}

// UpdateDocURL sets the "doc_url" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateDocURL() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateDocURL()
	})
}

// SetIconURL sets the "icon_url" field.
func (u *CatalogModelUpsertOne) SetIconURL(v string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetIconURL(v)
	})
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateIconURL() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateIconURL()
	})
}

// SetContextWindow sets the "context_window" field.
func (u *CatalogModelUpsertOne) SetContextWindow(v int64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetContextWindow(v)
	})
}

// AddContextWindow adds v to the "context_window" field.
func (u *CatalogModelUpsertOne) AddContextWindow(v int64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddContextWindow(v)
	})
}

// UpdateContextWindow sets the "context_window" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateContextWindow() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateContextWindow()
	})
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (u *CatalogModelUpsertOne) SetMaxOutputTokens(v int64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetMaxOutputTokens(v)
	})
}

// AddMaxOutputTokens adds v to the "max_output_tokens" field.
func (u *CatalogModelUpsertOne) AddMaxOutputTokens(v int64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddMaxOutputTokens(v)
	})
}

// UpdateMaxOutputTokens sets the "max_output_tokens" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateMaxOutputTokens() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateMaxOutputTokens()
	})
}

// SetInputModalities sets the "input_modalities" field.
func (u *CatalogModelUpsertOne) SetInputModalities(v []string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetInputModalities(v)
	})
}

// UpdateInputModalities sets the "input_modalities" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateInputModalities() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateInputModalities()
	})
}

// ClearInputModalities clears the value of the "input_modalities" field.
func (u *CatalogModelUpsertOne) ClearInputModalities() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearInputModalities()
	})
}

// SetOutputModalities sets the "output_modalities" field.
func (u *CatalogModelUpsertOne) SetOutputModalities(v []string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetOutputModalities(v)
	})
}

// UpdateOutputModalities sets the "output_modalities" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateOutputModalities() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateOutputModalities()
	})
}

// ClearOutputModalities clears the value of the "output_modalities" field.
func (u *CatalogModelUpsertOne) ClearOutputModalities() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearOutputModalities()
	})
}

// SetFeatures sets the "features" field.
func (u *CatalogModelUpsertOne) SetFeatures(v []string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateFeatures() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateFeatures()
	})
}

// ClearFeatures clears the value of the "features" field.
func (u *CatalogModelUpsertOne) ClearFeatures() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearFeatures()
	})
}

// SetInputPrice sets the "input_price" field.
func (u *CatalogModelUpsertOne) SetInputPrice(v float64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetInputPrice(v)
	})
}

// AddInputPrice adds v to the "input_price" field.
func (u *CatalogModelUpsertOne) AddInputPrice(v float64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddInputPrice(v)
	})
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateInputPrice() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateInputPrice()
	})
}

// SetOutputPrice sets the "output_price" field.
func (u *CatalogModelUpsertOne) SetOutputPrice(v float64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetOutputPrice(v)
	})
}

// AddOutputPrice adds v to the "output_price" field.
func (u *CatalogModelUpsertOne) AddOutputPrice(v float64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddOutputPrice(v)
	})
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateOutputPrice() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateOutputPrice()
	})
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *CatalogModelUpsertOne) SetCacheWritePrice(v float64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetCacheWritePrice(v)
	})
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *CatalogModelUpsertOne) AddCacheWritePrice(v float64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddCacheWritePrice(v)
	})
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateCacheWritePrice() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateCacheWritePrice()
	})
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *CatalogModelUpsertOne) ClearCacheWritePrice() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearCacheWritePrice()
	})
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *CatalogModelUpsertOne) SetCacheReadPrice(v float64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetCacheReadPrice(v)
	})
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *CatalogModelUpsertOne) AddCacheReadPrice(v float64) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddCacheReadPrice(v)
	})
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateCacheReadPrice() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateCacheReadPrice()
	})
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *CatalogModelUpsertOne) ClearCacheReadPrice() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearCacheReadPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *CatalogModelUpsertOne) SetCurrency(v string) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateCurrency() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateCurrency()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *CatalogModelUpsertOne) SetIsEnabled(v bool) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateIsEnabled() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateIsEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CatalogModelUpsertOne) SetUpdatedAt(v time.Time) *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CatalogModelUpsertOne) UpdateUpdatedAt() *CatalogModelUpsertOne {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CatalogModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CatalogModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CatalogModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CatalogModelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CatalogModelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CatalogModelCreateBulk is the builder for creating many CatalogModel entities in bulk.
type CatalogModelCreateBulk struct {
	config
	err      error
	builders []*CatalogModelCreate
	conflict []sql.ConflictOption
}

// Save creates the CatalogModel entities in the database.
func (_c *CatalogModelCreateBulk) Save(ctx context.Context) ([]*CatalogModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CatalogModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CatalogModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CatalogModelCreateBulk) SaveX(ctx context.Context) []*CatalogModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CatalogModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CatalogModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CatalogModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CatalogModelUpsert) {
//			SetModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *CatalogModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *CatalogModelUpsertBulk {
	_c.conflict = opts
	return &CatalogModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CatalogModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CatalogModelCreateBulk) OnConflictColumns(columns ...string) *CatalogModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CatalogModelUpsertBulk{
		create: _c,
	}
}

// CatalogModelUpsertBulk is the builder for "upsert"-ing
// a bulk of CatalogModel nodes.
type CatalogModelUpsertBulk struct {
	create *CatalogModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CatalogModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CatalogModelUpsertBulk) UpdateNewValues() *CatalogModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(catalogmodel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CatalogModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CatalogModelUpsertBulk) Ignore() *CatalogModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CatalogModelUpsertBulk) DoNothing() *CatalogModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CatalogModelCreateBulk.OnConflict
// documentation for more info.
func (u *CatalogModelUpsertBulk) Update(set func(*CatalogModelUpsert)) *CatalogModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CatalogModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelID sets the "model_id" field.
func (u *CatalogModelUpsertBulk) SetModelID(v string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateModelID() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateModelID()
	})
}

// SetName sets the "name" field.
func (u *CatalogModelUpsertBulk) SetName(v string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateName() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateName()
	})
}

// SetVendor sets the "vendor" field.
func (u *CatalogModelUpsertBulk) SetVendor(v string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetVendor(v)
	})
}

// UpdateVendor sets the "vendor" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateVendor() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateVendor()
	})
}

// SetCategory sets the "category" field.
func (u *CatalogModelUpsertBulk) SetCategory(v string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateCategory() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateCategory()
	})
}

// SetDescription sets the "description" field.
func (u *CatalogModelUpsertBulk) SetDescription(v string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateDescription() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateDescription()
	})
}

// SetTags sets the "tags" field.
func (u *CatalogModelUpsertBulk) SetTags(v []string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateTags() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *CatalogModelUpsertBulk) ClearTags() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearTags()
	})
}

// SetDocURL sets the "doc_url" field.
func (u *CatalogModelUpsertBulk) SetDocURL(v string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetDocURL(v)
	})
}

// UpdateDocURL sets the "doc_url" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateDocURL() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateDocURL()
	})
}

// SetIconURL sets the "icon_url" field.
func (u *CatalogModelUpsertBulk) SetIconURL(v string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetIconURL(v)
	})
}

// UpdateIconURL sets the "icon_url" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateIconURL() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateIconURL()
	})
}

// SetContextWindow sets the "context_window" field.
func (u *CatalogModelUpsertBulk) SetContextWindow(v int64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetContextWindow(v)
	})
}

// AddContextWindow adds v to the "context_window" field.
func (u *CatalogModelUpsertBulk) AddContextWindow(v int64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddContextWindow(v)
	})
}

// UpdateContextWindow sets the "context_window" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateContextWindow() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateContextWindow()
	})
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (u *CatalogModelUpsertBulk) SetMaxOutputTokens(v int64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetMaxOutputTokens(v)
	})
}

// AddMaxOutputTokens adds v to the "max_output_tokens" field.
func (u *CatalogModelUpsertBulk) AddMaxOutputTokens(v int64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddMaxOutputTokens(v)
	})
}

// UpdateMaxOutputTokens sets the "max_output_tokens" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateMaxOutputTokens() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateMaxOutputTokens()
	})
}

// SetInputModalities sets the "input_modalities" field.
func (u *CatalogModelUpsertBulk) SetInputModalities(v []string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetInputModalities(v)
	})
}

// UpdateInputModalities sets the "input_modalities" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateInputModalities() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateInputModalities()
	})
}

// ClearInputModalities clears the value of the "input_modalities" field.
func (u *CatalogModelUpsertBulk) ClearInputModalities() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearInputModalities()
	})
}

// SetOutputModalities sets the "output_modalities" field.
func (u *CatalogModelUpsertBulk) SetOutputModalities(v []string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetOutputModalities(v)
	})
}

// UpdateOutputModalities sets the "output_modalities" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateOutputModalities() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateOutputModalities()
	})
}

// ClearOutputModalities clears the value of the "output_modalities" field.
func (u *CatalogModelUpsertBulk) ClearOutputModalities() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearOutputModalities()
	})
}

// SetFeatures sets the "features" field.
func (u *CatalogModelUpsertBulk) SetFeatures(v []string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateFeatures() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateFeatures()
	})
}

// ClearFeatures clears the value of the "features" field.
func (u *CatalogModelUpsertBulk) ClearFeatures() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearFeatures()
	})
}

// SetInputPrice sets the "input_price" field.
func (u *CatalogModelUpsertBulk) SetInputPrice(v float64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetInputPrice(v)
	})
}

// AddInputPrice adds v to the "input_price" field.
func (u *CatalogModelUpsertBulk) AddInputPrice(v float64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddInputPrice(v)
	})
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateInputPrice() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateInputPrice()
	})
}

// SetOutputPrice sets the "output_price" field.
func (u *CatalogModelUpsertBulk) SetOutputPrice(v float64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetOutputPrice(v)
	})
}

// AddOutputPrice adds v to the "output_price" field.
func (u *CatalogModelUpsertBulk) AddOutputPrice(v float64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddOutputPrice(v)
	})
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateOutputPrice() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateOutputPrice()
	})
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *CatalogModelUpsertBulk) SetCacheWritePrice(v float64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetCacheWritePrice(v)
	})
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *CatalogModelUpsertBulk) AddCacheWritePrice(v float64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddCacheWritePrice(v)
	})
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateCacheWritePrice() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateCacheWritePrice()
	})
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *CatalogModelUpsertBulk) ClearCacheWritePrice() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearCacheWritePrice()
	})
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *CatalogModelUpsertBulk) SetCacheReadPrice(v float64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetCacheReadPrice(v)
	})
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *CatalogModelUpsertBulk) AddCacheReadPrice(v float64) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.AddCacheReadPrice(v)
	})
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateCacheReadPrice() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateCacheReadPrice()
	})
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *CatalogModelUpsertBulk) ClearCacheReadPrice() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.ClearCacheReadPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *CatalogModelUpsertBulk) SetCurrency(v string) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateCurrency() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateCurrency()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *CatalogModelUpsertBulk) SetIsEnabled(v bool) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateIsEnabled() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateIsEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CatalogModelUpsertBulk) SetUpdatedAt(v time.Time) *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CatalogModelUpsertBulk) UpdateUpdatedAt() *CatalogModelUpsertBulk {
	return u.Update(func(s *CatalogModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CatalogModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CatalogModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CatalogModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CatalogModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
