// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/mediagenerationtask"
)

// MediaGenerationTask is the model entity for the MediaGenerationTask schema.
type MediaGenerationTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 对外任务 ID
	TaskID string `json:"task_id,omitempty"`
	// 上游任务 ID
	UpstreamTaskID *string `json:"upstream_task_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// 提交时快照的用户订阅 ID，用于异步结算保持订阅计费语义
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// video/audio/image
	MediaType string `json:"media_type,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// BillingMetric holds the value of the "billing_metric" field.
	BillingMetric *string `json:"billing_metric,omitempty"`
	// ReservedCost holds the value of the "reserved_cost" field.
	ReservedCost float64 `json:"reserved_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost *float64 `json:"actual_cost,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// BillingCurrency holds the value of the "billing_currency" field.
	BillingCurrency string `json:"billing_currency,omitempty"`
	// RequestParams holds the value of the "request_params" field.
	RequestParams json.RawMessage `json:"request_params,omitempty"`
	// UpstreamUsage holds the value of the "upstream_usage" field.
	UpstreamUsage json.RawMessage `json:"upstream_usage,omitempty"`
	// 对客户端展示的结果视频链接（转存后为自有存储链接，否则为上游直链）
	ResultURL *string `json:"result_url,omitempty"`
	// 自有对象存储的对象键（转存成功时写入）
	ResultStorageKey *string `json:"result_storage_key,omitempty"`
	// PollAttempts holds the value of the "poll_attempts" field.
	PollAttempts int `json:"poll_attempts,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt *time.Time `json:"settled_at,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MediaGenerationTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mediagenerationtask.FieldRequestParams, mediagenerationtask.FieldUpstreamUsage:
			values[i] = new([]byte)
		case mediagenerationtask.FieldReservedCost, mediagenerationtask.FieldActualCost, mediagenerationtask.FieldRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case mediagenerationtask.FieldID, mediagenerationtask.FieldUserID, mediagenerationtask.FieldAPIKeyID, mediagenerationtask.FieldAccountID, mediagenerationtask.FieldGroupID, mediagenerationtask.FieldSubscriptionID, mediagenerationtask.FieldPollAttempts:
			values[i] = new(sql.NullInt64)
		case mediagenerationtask.FieldTaskID, mediagenerationtask.FieldUpstreamTaskID, mediagenerationtask.FieldModel, mediagenerationtask.FieldMediaType, mediagenerationtask.FieldStatus, mediagenerationtask.FieldBillingMetric, mediagenerationtask.FieldBillingCurrency, mediagenerationtask.FieldResultURL, mediagenerationtask.FieldResultStorageKey, mediagenerationtask.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case mediagenerationtask.FieldCreatedAt, mediagenerationtask.FieldUpdatedAt, mediagenerationtask.FieldExpiresAt, mediagenerationtask.FieldSettledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MediaGenerationTask fields.
func (_m *MediaGenerationTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mediagenerationtask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case mediagenerationtask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mediagenerationtask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mediagenerationtask.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case mediagenerationtask.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = new(string)
				*_m.UpstreamTaskID = value.String
			}
		case mediagenerationtask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case mediagenerationtask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case mediagenerationtask.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case mediagenerationtask.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case mediagenerationtask.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int64)
				*_m.SubscriptionID = value.Int64
			}
		case mediagenerationtask.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case mediagenerationtask.FieldMediaType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_type", values[i])
			} else if value.Valid {
				_m.MediaType = value.String
			}
		case mediagenerationtask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case mediagenerationtask.FieldBillingMetric:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_metric", values[i])
			} else if value.Valid {
				_m.BillingMetric = new(string)
				*_m.BillingMetric = value.String
			}
		case mediagenerationtask.FieldReservedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_cost", values[i])
			} else if value.Valid {
				_m.ReservedCost = value.Float64
			}
		case mediagenerationtask.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = new(float64)
				*_m.ActualCost = value.Float64
			}
		case mediagenerationtask.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case mediagenerationtask.FieldBillingCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_currency", values[i])
			} else if value.Valid {
				_m.BillingCurrency = value.String
			}
		case mediagenerationtask.FieldRequestParams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_params", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestParams); err != nil {
					return fmt.Errorf("unmarshal field request_params: %w", err)
				}
			}
		case mediagenerationtask.FieldUpstreamUsage:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_usage", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.UpstreamUsage); err != nil {
					return fmt.Errorf("unmarshal field upstream_usage: %w", err)
				}
			}
		case mediagenerationtask.FieldResultURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_url", values[i])
			} else if value.Valid {
				_m.ResultURL = new(string)
				*_m.ResultURL = value.String
			}
		case mediagenerationtask.FieldResultStorageKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_storage_key", values[i])
			} else if value.Valid {
				_m.ResultStorageKey = new(string)
				*_m.ResultStorageKey = value.String
			}
		case mediagenerationtask.FieldPollAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field poll_attempts", values[i])
			} else if value.Valid {
				_m.PollAttempts = int(value.Int64)
			}
		case mediagenerationtask.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case mediagenerationtask.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		case mediagenerationtask.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MediaGenerationTask.
// This includes values selected through modifiers, order, etc.
func (_m *MediaGenerationTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MediaGenerationTask.
// Note that you need to call MediaGenerationTask.Unwrap() before calling this method if this MediaGenerationTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MediaGenerationTask) Update() *MediaGenerationTaskUpdateOne {
	return NewMediaGenerationTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MediaGenerationTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MediaGenerationTask) Unwrap() *MediaGenerationTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MediaGenerationTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MediaGenerationTask) String() string {
	var builder strings.Builder
	builder.WriteString("MediaGenerationTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	if v := _m.UpstreamTaskID; v != nil {
		builder.WriteString("upstream_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("media_type=")
	builder.WriteString(_m.MediaType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.BillingMetric; v != nil {
		builder.WriteString("billing_metric=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("reserved_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservedCost))
	builder.WriteString(", ")
	if v := _m.ActualCost; v != nil {
		builder.WriteString("actual_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("billing_currency=")
	builder.WriteString(_m.BillingCurrency)
	builder.WriteString(", ")
	builder.WriteString("request_params=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestParams))
	builder.WriteString(", ")
	builder.WriteString("upstream_usage=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamUsage))
	builder.WriteString(", ")
	if v := _m.ResultURL; v != nil {
		builder.WriteString("result_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResultStorageKey; v != nil {
		builder.WriteString("result_storage_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("poll_attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollAttempts))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// MediaGenerationTasks is a parsable slice of MediaGenerationTask.
type MediaGenerationTasks []*MediaGenerationTask
