// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediagenerationtask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaGenerationTaskUpdate is the builder for updating MediaGenerationTask entities.
type MediaGenerationTaskUpdate struct {
	config
	hooks    []Hook
	mutation *MediaGenerationTaskMutation
}

// Where appends a list predicates to the MediaGenerationTaskUpdate builder.
func (_u *MediaGenerationTaskUpdate) Where(ps ...predicate.MediaGenerationTask) *MediaGenerationTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaGenerationTaskUpdate) SetUpdatedAt(v time.Time) *MediaGenerationTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *MediaGenerationTaskUpdate) SetTaskID(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableTaskID(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *MediaGenerationTaskUpdate) SetUpstreamTaskID(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableUpstreamTaskID(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *MediaGenerationTaskUpdate) ClearUpstreamTaskID() *MediaGenerationTaskUpdate {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MediaGenerationTaskUpdate) SetUserID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableUserID(v *int64) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MediaGenerationTaskUpdate) AddUserID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *MediaGenerationTaskUpdate) SetAPIKeyID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableAPIKeyID(v *int64) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *MediaGenerationTaskUpdate) AddAPIKeyID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *MediaGenerationTaskUpdate) SetAccountID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableAccountID(v *int64) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *MediaGenerationTaskUpdate) AddAccountID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *MediaGenerationTaskUpdate) ClearAccountID() *MediaGenerationTaskUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *MediaGenerationTaskUpdate) SetGroupID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableGroupID(v *int64) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *MediaGenerationTaskUpdate) AddGroupID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *MediaGenerationTaskUpdate) ClearGroupID() *MediaGenerationTaskUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *MediaGenerationTaskUpdate) SetSubscriptionID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableSubscriptionID(v *int64) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *MediaGenerationTaskUpdate) AddSubscriptionID(v int64) *MediaGenerationTaskUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *MediaGenerationTaskUpdate) ClearSubscriptionID() *MediaGenerationTaskUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetModel sets the "model" field.
func (_u *MediaGenerationTaskUpdate) SetModel(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableModel(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *MediaGenerationTaskUpdate) SetMediaType(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableMediaType(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaGenerationTaskUpdate) SetStatus(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableStatus(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBillingMetric sets the "billing_metric" field.
func (_u *MediaGenerationTaskUpdate) SetBillingMetric(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetBillingMetric(v)
	return _u
}

// SetNillableBillingMetric sets the "billing_metric" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableBillingMetric(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetBillingMetric(*v)
	}
	return _u
}

// ClearBillingMetric clears the value of the "billing_metric" field.
func (_u *MediaGenerationTaskUpdate) ClearBillingMetric() *MediaGenerationTaskUpdate {
	_u.mutation.ClearBillingMetric()
	return _u
}

// SetReservedCost sets the "reserved_cost" field.
func (_u *MediaGenerationTaskUpdate) SetReservedCost(v float64) *MediaGenerationTaskUpdate {
	_u.mutation.ResetReservedCost()
	_u.mutation.SetReservedCost(v)
	return _u
}

// SetNillableReservedCost sets the "reserved_cost" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableReservedCost(v *float64) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetReservedCost(*v)
	}
	return _u
}

// AddReservedCost adds value to the "reserved_cost" field.
func (_u *MediaGenerationTaskUpdate) AddReservedCost(v float64) *MediaGenerationTaskUpdate {
	_u.mutation.AddReservedCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *MediaGenerationTaskUpdate) SetActualCost(v float64) *MediaGenerationTaskUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableActualCost(v *float64) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *MediaGenerationTaskUpdate) AddActualCost(v float64) *MediaGenerationTaskUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *MediaGenerationTaskUpdate) ClearActualCost() *MediaGenerationTaskUpdate {
	_u.mutation.ClearActualCost()
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *MediaGenerationTaskUpdate) SetRateMultiplier(v float64) *MediaGenerationTaskUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableRateMultiplier(v *float64) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *MediaGenerationTaskUpdate) AddRateMultiplier(v float64) *MediaGenerationTaskUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetBillingCurrency sets the "billing_currency" field.
func (_u *MediaGenerationTaskUpdate) SetBillingCurrency(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetBillingCurrency(v)
	return _u
}

// SetNillableBillingCurrency sets the "billing_currency" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableBillingCurrency(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetBillingCurrency(*v)
	}
	return _u
}

// SetRequestParams sets the "request_params" field.
func (_u *MediaGenerationTaskUpdate) SetRequestParams(v json.RawMessage) *MediaGenerationTaskUpdate {
	_u.mutation.SetRequestParams(v)
	return _u
}

// AppendRequestParams appends value to the "request_params" field.
func (_u *MediaGenerationTaskUpdate) AppendRequestParams(v json.RawMessage) *MediaGenerationTaskUpdate {
	_u.mutation.AppendRequestParams(v)
	return _u
}

// ClearRequestParams clears the value of the "request_params" field.
func (_u *MediaGenerationTaskUpdate) ClearRequestParams() *MediaGenerationTaskUpdate {
	_u.mutation.ClearRequestParams()
	return _u
}

// SetUpstreamUsage sets the "upstream_usage" field.
func (_u *MediaGenerationTaskUpdate) SetUpstreamUsage(v json.RawMessage) *MediaGenerationTaskUpdate {
	_u.mutation.SetUpstreamUsage(v)
	return _u
}

// AppendUpstreamUsage appends value to the "upstream_usage" field.
func (_u *MediaGenerationTaskUpdate) AppendUpstreamUsage(v json.RawMessage) *MediaGenerationTaskUpdate {
	_u.mutation.AppendUpstreamUsage(v)
	return _u
}

// ClearUpstreamUsage clears the value of the "upstream_usage" field.
func (_u *MediaGenerationTaskUpdate) ClearUpstreamUsage() *MediaGenerationTaskUpdate {
	_u.mutation.ClearUpstreamUsage()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *MediaGenerationTaskUpdate) SetResultURL(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableResultURL(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *MediaGenerationTaskUpdate) ClearResultURL() *MediaGenerationTaskUpdate {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultStorageKey sets the "result_storage_key" field.
func (_u *MediaGenerationTaskUpdate) SetResultStorageKey(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetResultStorageKey(v)
	return _u
}

// SetNillableResultStorageKey sets the "result_storage_key" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableResultStorageKey(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetResultStorageKey(*v)
	}
	return _u
}

// ClearResultStorageKey clears the value of the "result_storage_key" field.
func (_u *MediaGenerationTaskUpdate) ClearResultStorageKey() *MediaGenerationTaskUpdate {
	_u.mutation.ClearResultStorageKey()
	return _u
}

// SetPollAttempts sets the "poll_attempts" field.
func (_u *MediaGenerationTaskUpdate) SetPollAttempts(v int) *MediaGenerationTaskUpdate {
	_u.mutation.ResetPollAttempts()
	_u.mutation.SetPollAttempts(v)
	return _u
}

// SetNillablePollAttempts sets the "poll_attempts" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillablePollAttempts(v *int) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetPollAttempts(*v)
	}
	return _u
}

// AddPollAttempts adds value to the "poll_attempts" field.
func (_u *MediaGenerationTaskUpdate) AddPollAttempts(v int) *MediaGenerationTaskUpdate {
	_u.mutation.AddPollAttempts(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MediaGenerationTaskUpdate) SetExpiresAt(v time.Time) *MediaGenerationTaskUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableExpiresAt(v *time.Time) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *MediaGenerationTaskUpdate) SetSettledAt(v time.Time) *MediaGenerationTaskUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableSettledAt(v *time.Time) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *MediaGenerationTaskUpdate) ClearSettledAt() *MediaGenerationTaskUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MediaGenerationTaskUpdate) SetErrorMessage(v string) *MediaGenerationTaskUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdate) SetNillableErrorMessage(v *string) *MediaGenerationTaskUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *MediaGenerationTaskUpdate) ClearErrorMessage() *MediaGenerationTaskUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the MediaGenerationTaskMutation object of the builder.
func (_u *MediaGenerationTaskUpdate) Mutation() *MediaGenerationTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaGenerationTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaGenerationTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaGenerationTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaGenerationTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaGenerationTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediagenerationtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaGenerationTaskUpdate) check() error {
	if v, ok := _u.mutation.TaskID(); ok {
		if err := mediagenerationtask.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := mediagenerationtask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := mediagenerationtask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaType(); ok {
		if err := mediagenerationtask.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.media_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediagenerationtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingMetric(); ok {
		if err := mediagenerationtask.BillingMetricValidator(v); err != nil {
			return &ValidationError{Name: "billing_metric", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.billing_metric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingCurrency(); ok {
		if err := mediagenerationtask.BillingCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "billing_currency", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.billing_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultStorageKey(); ok {
		if err := mediagenerationtask.ResultStorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "result_storage_key", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.result_storage_key": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaGenerationTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediagenerationtask.Table, mediagenerationtask.Columns, sqlgraph.NewFieldSpec(mediagenerationtask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediagenerationtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(mediagenerationtask.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(mediagenerationtask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(mediagenerationtask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mediagenerationtask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(mediagenerationtask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(mediagenerationtask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(mediagenerationtask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mediagenerationtask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(mediagenerationtask.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(mediagenerationtask.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(mediagenerationtask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(mediagenerationtask.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(mediagenerationtask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(mediagenerationtask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(mediagenerationtask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(mediagenerationtask.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(mediagenerationtask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(mediagenerationtask.FieldMediaType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediagenerationtask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingMetric(); ok {
		_spec.SetField(mediagenerationtask.FieldBillingMetric, field.TypeString, value)
	}
	if _u.mutation.BillingMetricCleared() {
		_spec.ClearField(mediagenerationtask.FieldBillingMetric, field.TypeString)
	}
	if value, ok := _u.mutation.ReservedCost(); ok {
		_spec.SetField(mediagenerationtask.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedCost(); ok {
		_spec.AddField(mediagenerationtask.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(mediagenerationtask.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(mediagenerationtask.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(mediagenerationtask.FieldActualCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(mediagenerationtask.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(mediagenerationtask.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BillingCurrency(); ok {
		_spec.SetField(mediagenerationtask.FieldBillingCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestParams(); ok {
		_spec.SetField(mediagenerationtask.FieldRequestParams, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestParams(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediagenerationtask.FieldRequestParams, value)
		})
	}
	if _u.mutation.RequestParamsCleared() {
		_spec.ClearField(mediagenerationtask.FieldRequestParams, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpstreamUsage(); ok {
		_spec.SetField(mediagenerationtask.FieldUpstreamUsage, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUpstreamUsage(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediagenerationtask.FieldUpstreamUsage, value)
		})
	}
	if _u.mutation.UpstreamUsageCleared() {
		_spec.ClearField(mediagenerationtask.FieldUpstreamUsage, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(mediagenerationtask.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(mediagenerationtask.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultStorageKey(); ok {
		_spec.SetField(mediagenerationtask.FieldResultStorageKey, field.TypeString, value)
	}
	if _u.mutation.ResultStorageKeyCleared() {
		_spec.ClearField(mediagenerationtask.FieldResultStorageKey, field.TypeString)
	}
	if value, ok := _u.mutation.PollAttempts(); ok {
		_spec.SetField(mediagenerationtask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollAttempts(); ok {
		_spec.AddField(mediagenerationtask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(mediagenerationtask.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(mediagenerationtask.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(mediagenerationtask.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(mediagenerationtask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(mediagenerationtask.FieldErrorMessage, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediagenerationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaGenerationTaskUpdateOne is the builder for updating a single MediaGenerationTask entity.
type MediaGenerationTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaGenerationTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaGenerationTaskUpdateOne) SetUpdatedAt(v time.Time) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *MediaGenerationTaskUpdateOne) SetTaskID(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableTaskID(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *MediaGenerationTaskUpdateOne) SetUpstreamTaskID(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableUpstreamTaskID(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *MediaGenerationTaskUpdateOne) ClearUpstreamTaskID() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MediaGenerationTaskUpdateOne) SetUserID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableUserID(v *int64) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MediaGenerationTaskUpdateOne) AddUserID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *MediaGenerationTaskUpdateOne) SetAPIKeyID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableAPIKeyID(v *int64) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *MediaGenerationTaskUpdateOne) AddAPIKeyID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *MediaGenerationTaskUpdateOne) SetAccountID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableAccountID(v *int64) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *MediaGenerationTaskUpdateOne) AddAccountID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *MediaGenerationTaskUpdateOne) ClearAccountID() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *MediaGenerationTaskUpdateOne) SetGroupID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableGroupID(v *int64) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *MediaGenerationTaskUpdateOne) AddGroupID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *MediaGenerationTaskUpdateOne) ClearGroupID() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *MediaGenerationTaskUpdateOne) SetSubscriptionID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableSubscriptionID(v *int64) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *MediaGenerationTaskUpdateOne) AddSubscriptionID(v int64) *MediaGenerationTaskUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *MediaGenerationTaskUpdateOne) ClearSubscriptionID() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetModel sets the "model" field.
func (_u *MediaGenerationTaskUpdateOne) SetModel(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableModel(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *MediaGenerationTaskUpdateOne) SetMediaType(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableMediaType(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaGenerationTaskUpdateOne) SetStatus(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableStatus(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetBillingMetric sets the "billing_metric" field.
func (_u *MediaGenerationTaskUpdateOne) SetBillingMetric(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetBillingMetric(v)
	return _u
}

// SetNillableBillingMetric sets the "billing_metric" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableBillingMetric(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetBillingMetric(*v)
	}
	return _u
}

// ClearBillingMetric clears the value of the "billing_metric" field.
func (_u *MediaGenerationTaskUpdateOne) ClearBillingMetric() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearBillingMetric()
	return _u
}

// SetReservedCost sets the "reserved_cost" field.
func (_u *MediaGenerationTaskUpdateOne) SetReservedCost(v float64) *MediaGenerationTaskUpdateOne {
	_u.mutation.ResetReservedCost()
	_u.mutation.SetReservedCost(v)
	return _u
}

// SetNillableReservedCost sets the "reserved_cost" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableReservedCost(v *float64) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetReservedCost(*v)
	}
	return _u
}

// AddReservedCost adds value to the "reserved_cost" field.
func (_u *MediaGenerationTaskUpdateOne) AddReservedCost(v float64) *MediaGenerationTaskUpdateOne {
	_u.mutation.AddReservedCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *MediaGenerationTaskUpdateOne) SetActualCost(v float64) *MediaGenerationTaskUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableActualCost(v *float64) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *MediaGenerationTaskUpdateOne) AddActualCost(v float64) *MediaGenerationTaskUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *MediaGenerationTaskUpdateOne) ClearActualCost() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearActualCost()
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *MediaGenerationTaskUpdateOne) SetRateMultiplier(v float64) *MediaGenerationTaskUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableRateMultiplier(v *float64) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *MediaGenerationTaskUpdateOne) AddRateMultiplier(v float64) *MediaGenerationTaskUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetBillingCurrency sets the "billing_currency" field.
func (_u *MediaGenerationTaskUpdateOne) SetBillingCurrency(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetBillingCurrency(v)
	return _u
}

// SetNillableBillingCurrency sets the "billing_currency" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableBillingCurrency(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetBillingCurrency(*v)
	}
	return _u
}

// SetRequestParams sets the "request_params" field.
func (_u *MediaGenerationTaskUpdateOne) SetRequestParams(v json.RawMessage) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetRequestParams(v)
	return _u
}

// AppendRequestParams appends value to the "request_params" field.
func (_u *MediaGenerationTaskUpdateOne) AppendRequestParams(v json.RawMessage) *MediaGenerationTaskUpdateOne {
	_u.mutation.AppendRequestParams(v)
	return _u
}

// ClearRequestParams clears the value of the "request_params" field.
func (_u *MediaGenerationTaskUpdateOne) ClearRequestParams() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearRequestParams()
	return _u
}

// SetUpstreamUsage sets the "upstream_usage" field.
func (_u *MediaGenerationTaskUpdateOne) SetUpstreamUsage(v json.RawMessage) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetUpstreamUsage(v)
	return _u
}

// AppendUpstreamUsage appends value to the "upstream_usage" field.
func (_u *MediaGenerationTaskUpdateOne) AppendUpstreamUsage(v json.RawMessage) *MediaGenerationTaskUpdateOne {
	_u.mutation.AppendUpstreamUsage(v)
	return _u
}

// ClearUpstreamUsage clears the value of the "upstream_usage" field.
func (_u *MediaGenerationTaskUpdateOne) ClearUpstreamUsage() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearUpstreamUsage()
	return _u
}

// SetResultURL sets the "result_url" field.
func (_u *MediaGenerationTaskUpdateOne) SetResultURL(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetResultURL(v)
	return _u
}

// SetNillableResultURL sets the "result_url" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableResultURL(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetResultURL(*v)
	}
	return _u
}

// ClearResultURL clears the value of the "result_url" field.
func (_u *MediaGenerationTaskUpdateOne) ClearResultURL() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearResultURL()
	return _u
}

// SetResultStorageKey sets the "result_storage_key" field.
func (_u *MediaGenerationTaskUpdateOne) SetResultStorageKey(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetResultStorageKey(v)
	return _u
}

// SetNillableResultStorageKey sets the "result_storage_key" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableResultStorageKey(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetResultStorageKey(*v)
	}
	return _u
}

// ClearResultStorageKey clears the value of the "result_storage_key" field.
func (_u *MediaGenerationTaskUpdateOne) ClearResultStorageKey() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearResultStorageKey()
	return _u
}

// SetPollAttempts sets the "poll_attempts" field.
func (_u *MediaGenerationTaskUpdateOne) SetPollAttempts(v int) *MediaGenerationTaskUpdateOne {
	_u.mutation.ResetPollAttempts()
	_u.mutation.SetPollAttempts(v)
	return _u
}

// SetNillablePollAttempts sets the "poll_attempts" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillablePollAttempts(v *int) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetPollAttempts(*v)
	}
	return _u
}

// AddPollAttempts adds value to the "poll_attempts" field.
func (_u *MediaGenerationTaskUpdateOne) AddPollAttempts(v int) *MediaGenerationTaskUpdateOne {
	_u.mutation.AddPollAttempts(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *MediaGenerationTaskUpdateOne) SetExpiresAt(v time.Time) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableExpiresAt(v *time.Time) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *MediaGenerationTaskUpdateOne) SetSettledAt(v time.Time) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableSettledAt(v *time.Time) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *MediaGenerationTaskUpdateOne) ClearSettledAt() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MediaGenerationTaskUpdateOne) SetErrorMessage(v string) *MediaGenerationTaskUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MediaGenerationTaskUpdateOne) SetNillableErrorMessage(v *string) *MediaGenerationTaskUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *MediaGenerationTaskUpdateOne) ClearErrorMessage() *MediaGenerationTaskUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the MediaGenerationTaskMutation object of the builder.
func (_u *MediaGenerationTaskUpdateOne) Mutation() *MediaGenerationTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the MediaGenerationTaskUpdate builder.
func (_u *MediaGenerationTaskUpdateOne) Where(ps ...predicate.MediaGenerationTask) *MediaGenerationTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaGenerationTaskUpdateOne) Select(field string, fields ...string) *MediaGenerationTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaGenerationTask entity.
func (_u *MediaGenerationTaskUpdateOne) Save(ctx context.Context) (*MediaGenerationTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaGenerationTaskUpdateOne) SaveX(ctx context.Context) *MediaGenerationTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaGenerationTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaGenerationTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaGenerationTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediagenerationtask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaGenerationTaskUpdateOne) check() error {
	if v, ok := _u.mutation.TaskID(); ok {
		if err := mediagenerationtask.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := mediagenerationtask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := mediagenerationtask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaType(); ok {
		if err := mediagenerationtask.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.media_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediagenerationtask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingMetric(); ok {
		if err := mediagenerationtask.BillingMetricValidator(v); err != nil {
			return &ValidationError{Name: "billing_metric", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.billing_metric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingCurrency(); ok {
		if err := mediagenerationtask.BillingCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "billing_currency", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.billing_currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultStorageKey(); ok {
		if err := mediagenerationtask.ResultStorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "result_storage_key", err: fmt.Errorf(`ent: validator failed for field "MediaGenerationTask.result_storage_key": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaGenerationTaskUpdateOne) sqlSave(ctx context.Context) (_node *MediaGenerationTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediagenerationtask.Table, mediagenerationtask.Columns, sqlgraph.NewFieldSpec(mediagenerationtask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaGenerationTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediagenerationtask.FieldID)
		for _, f := range fields {
			if !mediagenerationtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediagenerationtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediagenerationtask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(mediagenerationtask.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(mediagenerationtask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(mediagenerationtask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mediagenerationtask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(mediagenerationtask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(mediagenerationtask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(mediagenerationtask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mediagenerationtask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(mediagenerationtask.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(mediagenerationtask.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(mediagenerationtask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(mediagenerationtask.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(mediagenerationtask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(mediagenerationtask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(mediagenerationtask.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(mediagenerationtask.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(mediagenerationtask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(mediagenerationtask.FieldMediaType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediagenerationtask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.BillingMetric(); ok {
		_spec.SetField(mediagenerationtask.FieldBillingMetric, field.TypeString, value)
	}
	if _u.mutation.BillingMetricCleared() {
		_spec.ClearField(mediagenerationtask.FieldBillingMetric, field.TypeString)
	}
	if value, ok := _u.mutation.ReservedCost(); ok {
		_spec.SetField(mediagenerationtask.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedCost(); ok {
		_spec.AddField(mediagenerationtask.FieldReservedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(mediagenerationtask.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(mediagenerationtask.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(mediagenerationtask.FieldActualCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(mediagenerationtask.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(mediagenerationtask.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BillingCurrency(); ok {
		_spec.SetField(mediagenerationtask.FieldBillingCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestParams(); ok {
		_spec.SetField(mediagenerationtask.FieldRequestParams, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRequestParams(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediagenerationtask.FieldRequestParams, value)
		})
	}
	if _u.mutation.RequestParamsCleared() {
		_spec.ClearField(mediagenerationtask.FieldRequestParams, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpstreamUsage(); ok {
		_spec.SetField(mediagenerationtask.FieldUpstreamUsage, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUpstreamUsage(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mediagenerationtask.FieldUpstreamUsage, value)
		})
	}
	if _u.mutation.UpstreamUsageCleared() {
		_spec.ClearField(mediagenerationtask.FieldUpstreamUsage, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultURL(); ok {
		_spec.SetField(mediagenerationtask.FieldResultURL, field.TypeString, value)
	}
	if _u.mutation.ResultURLCleared() {
		_spec.ClearField(mediagenerationtask.FieldResultURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResultStorageKey(); ok {
		_spec.SetField(mediagenerationtask.FieldResultStorageKey, field.TypeString, value)
	}
	if _u.mutation.ResultStorageKeyCleared() {
		_spec.ClearField(mediagenerationtask.FieldResultStorageKey, field.TypeString)
	}
	if value, ok := _u.mutation.PollAttempts(); ok {
		_spec.SetField(mediagenerationtask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollAttempts(); ok {
		_spec.AddField(mediagenerationtask.FieldPollAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(mediagenerationtask.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(mediagenerationtask.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(mediagenerationtask.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(mediagenerationtask.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(mediagenerationtask.FieldErrorMessage, field.TypeString)
	}
	_node = &MediaGenerationTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediagenerationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
