// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/mediaquotahold"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MediaQuotaHoldUpdate is the builder for updating MediaQuotaHold entities.
type MediaQuotaHoldUpdate struct {
	config
	hooks    []Hook
	mutation *MediaQuotaHoldMutation
}

// Where appends a list predicates to the MediaQuotaHoldUpdate builder.
func (_u *MediaQuotaHoldUpdate) Where(ps ...predicate.MediaQuotaHold) *MediaQuotaHoldUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaQuotaHoldUpdate) SetUpdatedAt(v time.Time) *MediaQuotaHoldUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHoldID sets the "hold_id" field.
func (_u *MediaQuotaHoldUpdate) SetHoldID(v string) *MediaQuotaHoldUpdate {
	_u.mutation.SetHoldID(v)
	return _u
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdate) SetNillableHoldID(v *string) *MediaQuotaHoldUpdate {
	if v != nil {
		_u.SetHoldID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *MediaQuotaHoldUpdate) SetTaskID(v string) *MediaQuotaHoldUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdate) SetNillableTaskID(v *string) *MediaQuotaHoldUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MediaQuotaHoldUpdate) SetUserID(v int64) *MediaQuotaHoldUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdate) SetNillableUserID(v *int64) *MediaQuotaHoldUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MediaQuotaHoldUpdate) AddUserID(v int64) *MediaQuotaHoldUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *MediaQuotaHoldUpdate) SetAmount(v float64) *MediaQuotaHoldUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdate) SetNillableAmount(v *float64) *MediaQuotaHoldUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *MediaQuotaHoldUpdate) AddAmount(v float64) *MediaQuotaHoldUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *MediaQuotaHoldUpdate) SetCurrency(v string) *MediaQuotaHoldUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdate) SetNillableCurrency(v *string) *MediaQuotaHoldUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaQuotaHoldUpdate) SetStatus(v string) *MediaQuotaHoldUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdate) SetNillableStatus(v *string) *MediaQuotaHoldUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the MediaQuotaHoldMutation object of the builder.
func (_u *MediaQuotaHoldUpdate) Mutation() *MediaQuotaHoldMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaQuotaHoldUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaQuotaHoldUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaQuotaHoldUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaQuotaHoldUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaQuotaHoldUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediaquotahold.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaQuotaHoldUpdate) check() error {
	if v, ok := _u.mutation.HoldID(); ok {
		if err := mediaquotahold.HoldIDValidator(v); err != nil {
			return &ValidationError{Name: "hold_id", err: fmt.Errorf(`ent: validator failed for field "MediaQuotaHold.hold_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskID(); ok {
		if err := mediaquotahold.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "MediaQuotaHold.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := mediaquotahold.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "MediaQuotaHold.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediaquotahold.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaQuotaHold.status": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaQuotaHoldUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaquotahold.Table, mediaquotahold.Columns, sqlgraph.NewFieldSpec(mediaquotahold.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaquotahold.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HoldID(); ok {
		_spec.SetField(mediaquotahold.FieldHoldID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(mediaquotahold.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mediaquotahold.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(mediaquotahold.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(mediaquotahold.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(mediaquotahold.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(mediaquotahold.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediaquotahold.FieldStatus, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaquotahold.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaQuotaHoldUpdateOne is the builder for updating a single MediaQuotaHold entity.
type MediaQuotaHoldUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaQuotaHoldMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaQuotaHoldUpdateOne) SetUpdatedAt(v time.Time) *MediaQuotaHoldUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetHoldID sets the "hold_id" field.
func (_u *MediaQuotaHoldUpdateOne) SetHoldID(v string) *MediaQuotaHoldUpdateOne {
	_u.mutation.SetHoldID(v)
	return _u
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdateOne) SetNillableHoldID(v *string) *MediaQuotaHoldUpdateOne {
	if v != nil {
		_u.SetHoldID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *MediaQuotaHoldUpdateOne) SetTaskID(v string) *MediaQuotaHoldUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdateOne) SetNillableTaskID(v *string) *MediaQuotaHoldUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MediaQuotaHoldUpdateOne) SetUserID(v int64) *MediaQuotaHoldUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdateOne) SetNillableUserID(v *int64) *MediaQuotaHoldUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *MediaQuotaHoldUpdateOne) AddUserID(v int64) *MediaQuotaHoldUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *MediaQuotaHoldUpdateOne) SetAmount(v float64) *MediaQuotaHoldUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdateOne) SetNillableAmount(v *float64) *MediaQuotaHoldUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *MediaQuotaHoldUpdateOne) AddAmount(v float64) *MediaQuotaHoldUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *MediaQuotaHoldUpdateOne) SetCurrency(v string) *MediaQuotaHoldUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdateOne) SetNillableCurrency(v *string) *MediaQuotaHoldUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaQuotaHoldUpdateOne) SetStatus(v string) *MediaQuotaHoldUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaQuotaHoldUpdateOne) SetNillableStatus(v *string) *MediaQuotaHoldUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the MediaQuotaHoldMutation object of the builder.
func (_u *MediaQuotaHoldUpdateOne) Mutation() *MediaQuotaHoldMutation {
	return _u.mutation
}

// Where appends a list predicates to the MediaQuotaHoldUpdate builder.
func (_u *MediaQuotaHoldUpdateOne) Where(ps ...predicate.MediaQuotaHold) *MediaQuotaHoldUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaQuotaHoldUpdateOne) Select(field string, fields ...string) *MediaQuotaHoldUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaQuotaHold entity.
func (_u *MediaQuotaHoldUpdateOne) Save(ctx context.Context) (*MediaQuotaHold, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaQuotaHoldUpdateOne) SaveX(ctx context.Context) *MediaQuotaHold {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaQuotaHoldUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaQuotaHoldUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaQuotaHoldUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediaquotahold.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaQuotaHoldUpdateOne) check() error {
	if v, ok := _u.mutation.HoldID(); ok {
		if err := mediaquotahold.HoldIDValidator(v); err != nil {
			return &ValidationError{Name: "hold_id", err: fmt.Errorf(`ent: validator failed for field "MediaQuotaHold.hold_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskID(); ok {
		if err := mediaquotahold.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "MediaQuotaHold.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := mediaquotahold.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "MediaQuotaHold.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediaquotahold.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaQuotaHold.status": %w`, err)}
		}
	}
	return nil
}

func (_u *MediaQuotaHoldUpdateOne) sqlSave(ctx context.Context) (_node *MediaQuotaHold, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediaquotahold.Table, mediaquotahold.Columns, sqlgraph.NewFieldSpec(mediaquotahold.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaQuotaHold.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediaquotahold.FieldID)
		for _, f := range fields {
			if !mediaquotahold.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediaquotahold.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediaquotahold.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HoldID(); ok {
		_spec.SetField(mediaquotahold.FieldHoldID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(mediaquotahold.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(mediaquotahold.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(mediaquotahold.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(mediaquotahold.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(mediaquotahold.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(mediaquotahold.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediaquotahold.FieldStatus, field.TypeString, value)
	}
	_node = &MediaQuotaHold{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediaquotahold.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
