// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/voucherorder"
)

// VoucherOrderUpdate is the builder for updating VoucherOrder entities.
type VoucherOrderUpdate struct {
	config
	hooks    []Hook
	mutation *VoucherOrderMutation
}

// Where appends a list predicates to the VoucherOrderUpdate builder.
func (_u *VoucherOrderUpdate) Where(ps ...predicate.VoucherOrder) *VoucherOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *VoucherOrderUpdate) SetOrderNo(v string) *VoucherOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableOrderNo(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VoucherOrderUpdate) SetUserID(v int64) *VoucherOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableUserID(v *int64) *VoucherOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *VoucherOrderUpdate) SetUserEmail(v string) *VoucherOrderUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableUserEmail(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *VoucherOrderUpdate) SetUserName(v string) *VoucherOrderUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableUserName(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VoucherOrderUpdate) SetStatus(v string) *VoucherOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableStatus(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *VoucherOrderUpdate) SetProductID(v int64) *VoucherOrderUpdate {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableProductID(v *int64) *VoucherOrderUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *VoucherOrderUpdate) AddProductID(v int64) *VoucherOrderUpdate {
	_u.mutation.AddProductID(v)
	return _u
}

// SetKvProductID sets the "kv_product_id" field.
func (_u *VoucherOrderUpdate) SetKvProductID(v int64) *VoucherOrderUpdate {
	_u.mutation.ResetKvProductID()
	_u.mutation.SetKvProductID(v)
	return _u
}

// SetNillableKvProductID sets the "kv_product_id" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableKvProductID(v *int64) *VoucherOrderUpdate {
	if v != nil {
		_u.SetKvProductID(*v)
	}
	return _u
}

// AddKvProductID adds value to the "kv_product_id" field.
func (_u *VoucherOrderUpdate) AddKvProductID(v int64) *VoucherOrderUpdate {
	_u.mutation.AddKvProductID(v)
	return _u
}

// ClearKvProductID clears the value of the "kv_product_id" field.
func (_u *VoucherOrderUpdate) ClearKvProductID() *VoucherOrderUpdate {
	_u.mutation.ClearKvProductID()
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *VoucherOrderUpdate) SetProductName(v string) *VoucherOrderUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableProductName(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetDenomination sets the "denomination" field.
func (_u *VoucherOrderUpdate) SetDenomination(v float64) *VoucherOrderUpdate {
	_u.mutation.ResetDenomination()
	_u.mutation.SetDenomination(v)
	return _u
}

// SetNillableDenomination sets the "denomination" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableDenomination(v *float64) *VoucherOrderUpdate {
	if v != nil {
		_u.SetDenomination(*v)
	}
	return _u
}

// AddDenomination adds value to the "denomination" field.
func (_u *VoucherOrderUpdate) AddDenomination(v float64) *VoucherOrderUpdate {
	_u.mutation.AddDenomination(v)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *VoucherOrderUpdate) SetQuantity(v int) *VoucherOrderUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableQuantity(v *int) *VoucherOrderUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *VoucherOrderUpdate) AddQuantity(v int) *VoucherOrderUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *VoucherOrderUpdate) SetUnitPrice(v float64) *VoucherOrderUpdate {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableUnitPrice(v *float64) *VoucherOrderUpdate {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *VoucherOrderUpdate) AddUnitPrice(v float64) *VoucherOrderUpdate {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetSubtotal sets the "subtotal" field.
func (_u *VoucherOrderUpdate) SetSubtotal(v float64) *VoucherOrderUpdate {
	_u.mutation.ResetSubtotal()
	_u.mutation.SetSubtotal(v)
	return _u
}

// SetNillableSubtotal sets the "subtotal" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableSubtotal(v *float64) *VoucherOrderUpdate {
	if v != nil {
		_u.SetSubtotal(*v)
	}
	return _u
}

// AddSubtotal adds value to the "subtotal" field.
func (_u *VoucherOrderUpdate) AddSubtotal(v float64) *VoucherOrderUpdate {
	_u.mutation.AddSubtotal(v)
	return _u
}

// SetFeeAmount sets the "fee_amount" field.
func (_u *VoucherOrderUpdate) SetFeeAmount(v float64) *VoucherOrderUpdate {
	_u.mutation.ResetFeeAmount()
	_u.mutation.SetFeeAmount(v)
	return _u
}

// SetNillableFeeAmount sets the "fee_amount" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableFeeAmount(v *float64) *VoucherOrderUpdate {
	if v != nil {
		_u.SetFeeAmount(*v)
	}
	return _u
}

// AddFeeAmount adds value to the "fee_amount" field.
func (_u *VoucherOrderUpdate) AddFeeAmount(v float64) *VoucherOrderUpdate {
	_u.mutation.AddFeeAmount(v)
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *VoucherOrderUpdate) SetTotalAmount(v float64) *VoucherOrderUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableTotalAmount(v *float64) *VoucherOrderUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *VoucherOrderUpdate) AddTotalAmount(v float64) *VoucherOrderUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *VoucherOrderUpdate) SetCurrency(v string) *VoucherOrderUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableCurrency(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetPaymentRef sets the "payment_ref" field.
func (_u *VoucherOrderUpdate) SetPaymentRef(v string) *VoucherOrderUpdate {
	_u.mutation.SetPaymentRef(v)
	return _u
}

// SetNillablePaymentRef sets the "payment_ref" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillablePaymentRef(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetPaymentRef(*v)
	}
	return _u
}

// ClearPaymentRef clears the value of the "payment_ref" field.
func (_u *VoucherOrderUpdate) ClearPaymentRef() *VoucherOrderUpdate {
	_u.mutation.ClearPaymentRef()
	return _u
}

// SetPaymentProofPath sets the "payment_proof_path" field.
func (_u *VoucherOrderUpdate) SetPaymentProofPath(v string) *VoucherOrderUpdate {
	_u.mutation.SetPaymentProofPath(v)
	return _u
}

// SetNillablePaymentProofPath sets the "payment_proof_path" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillablePaymentProofPath(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetPaymentProofPath(*v)
	}
	return _u
}

// ClearPaymentProofPath clears the value of the "payment_proof_path" field.
func (_u *VoucherOrderUpdate) ClearPaymentProofPath() *VoucherOrderUpdate {
	_u.mutation.ClearPaymentProofPath()
	return _u
}

// SetBankAccountID sets the "bank_account_id" field.
func (_u *VoucherOrderUpdate) SetBankAccountID(v int) *VoucherOrderUpdate {
	_u.mutation.ResetBankAccountID()
	_u.mutation.SetBankAccountID(v)
	return _u
}

// SetNillableBankAccountID sets the "bank_account_id" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableBankAccountID(v *int) *VoucherOrderUpdate {
	if v != nil {
		_u.SetBankAccountID(*v)
	}
	return _u
}

// AddBankAccountID adds value to the "bank_account_id" field.
func (_u *VoucherOrderUpdate) AddBankAccountID(v int) *VoucherOrderUpdate {
	_u.mutation.AddBankAccountID(v)
	return _u
}

// ClearBankAccountID clears the value of the "bank_account_id" field.
func (_u *VoucherOrderUpdate) ClearBankAccountID() *VoucherOrderUpdate {
	_u.mutation.ClearBankAccountID()
	return _u
}

// SetKvRetrieveReference sets the "kv_retrieve_reference" field.
func (_u *VoucherOrderUpdate) SetKvRetrieveReference(v string) *VoucherOrderUpdate {
	_u.mutation.SetKvRetrieveReference(v)
	return _u
}

// SetNillableKvRetrieveReference sets the "kv_retrieve_reference" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableKvRetrieveReference(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetKvRetrieveReference(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *VoucherOrderUpdate) SetIdempotencyKey(v string) *VoucherOrderUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableIdempotencyKey(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *VoucherOrderUpdate) ClearIdempotencyKey() *VoucherOrderUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *VoucherOrderUpdate) SetRejectReason(v string) *VoucherOrderUpdate {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableRejectReason(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *VoucherOrderUpdate) ClearRejectReason() *VoucherOrderUpdate {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetFulfillError sets the "fulfill_error" field.
func (_u *VoucherOrderUpdate) SetFulfillError(v string) *VoucherOrderUpdate {
	_u.mutation.SetFulfillError(v)
	return _u
}

// SetNillableFulfillError sets the "fulfill_error" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableFulfillError(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetFulfillError(*v)
	}
	return _u
}

// ClearFulfillError clears the value of the "fulfill_error" field.
func (_u *VoucherOrderUpdate) ClearFulfillError() *VoucherOrderUpdate {
	_u.mutation.ClearFulfillError()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *VoucherOrderUpdate) SetExpiresAt(v time.Time) *VoucherOrderUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableExpiresAt(v *time.Time) *VoucherOrderUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *VoucherOrderUpdate) SetVerifiedAt(v time.Time) *VoucherOrderUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableVerifiedAt(v *time.Time) *VoucherOrderUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *VoucherOrderUpdate) ClearVerifiedAt() *VoucherOrderUpdate {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (_u *VoucherOrderUpdate) SetFulfilledAt(v time.Time) *VoucherOrderUpdate {
	_u.mutation.SetFulfilledAt(v)
	return _u
}

// SetNillableFulfilledAt sets the "fulfilled_at" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableFulfilledAt(v *time.Time) *VoucherOrderUpdate {
	if v != nil {
		_u.SetFulfilledAt(*v)
	}
	return _u
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (_u *VoucherOrderUpdate) ClearFulfilledAt() *VoucherOrderUpdate {
	_u.mutation.ClearFulfilledAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *VoucherOrderUpdate) SetCompletedAt(v time.Time) *VoucherOrderUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableCompletedAt(v *time.Time) *VoucherOrderUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *VoucherOrderUpdate) ClearCompletedAt() *VoucherOrderUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *VoucherOrderUpdate) SetClientIP(v string) *VoucherOrderUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *VoucherOrderUpdate) SetNillableClientIP(v *string) *VoucherOrderUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VoucherOrderUpdate) SetUpdatedAt(v time.Time) *VoucherOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VoucherOrderUpdate) SetUser(v *User) *VoucherOrderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the VoucherOrderMutation object of the builder.
func (_u *VoucherOrderUpdate) Mutation() *VoucherOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VoucherOrderUpdate) ClearUser() *VoucherOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VoucherOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoucherOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VoucherOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoucherOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VoucherOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := voucherorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoucherOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := voucherorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := voucherorder.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserName(); ok {
		if err := voucherorder.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.user_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := voucherorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := voucherorder.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := voucherorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentRef(); ok {
		if err := voucherorder.PaymentRefValidator(v); err != nil {
			return &ValidationError{Name: "payment_ref", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.payment_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentProofPath(); ok {
		if err := voucherorder.PaymentProofPathValidator(v); err != nil {
			return &ValidationError{Name: "payment_proof_path", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.payment_proof_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KvRetrieveReference(); ok {
		if err := voucherorder.KvRetrieveReferenceValidator(v); err != nil {
			return &ValidationError{Name: "kv_retrieve_reference", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.kv_retrieve_reference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := voucherorder.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := voucherorder.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.client_ip": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoucherOrder.user"`)
	}
	return nil
}

func (_u *VoucherOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(voucherorder.Table, voucherorder.Columns, sqlgraph.NewFieldSpec(voucherorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(voucherorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(voucherorder.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(voucherorder.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(voucherorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(voucherorder.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(voucherorder.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KvProductID(); ok {
		_spec.SetField(voucherorder.FieldKvProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedKvProductID(); ok {
		_spec.AddField(voucherorder.FieldKvProductID, field.TypeInt64, value)
	}
	if _u.mutation.KvProductIDCleared() {
		_spec.ClearField(voucherorder.FieldKvProductID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(voucherorder.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Denomination(); ok {
		_spec.SetField(voucherorder.FieldDenomination, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDenomination(); ok {
		_spec.AddField(voucherorder.FieldDenomination, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(voucherorder.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(voucherorder.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(voucherorder.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(voucherorder.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Subtotal(); ok {
		_spec.SetField(voucherorder.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSubtotal(); ok {
		_spec.AddField(voucherorder.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeAmount(); ok {
		_spec.SetField(voucherorder.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeAmount(); ok {
		_spec.AddField(voucherorder.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(voucherorder.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(voucherorder.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(voucherorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentRef(); ok {
		_spec.SetField(voucherorder.FieldPaymentRef, field.TypeString, value)
	}
	if _u.mutation.PaymentRefCleared() {
		_spec.ClearField(voucherorder.FieldPaymentRef, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentProofPath(); ok {
		_spec.SetField(voucherorder.FieldPaymentProofPath, field.TypeString, value)
	}
	if _u.mutation.PaymentProofPathCleared() {
		_spec.ClearField(voucherorder.FieldPaymentProofPath, field.TypeString)
	}
	if value, ok := _u.mutation.BankAccountID(); ok {
		_spec.SetField(voucherorder.FieldBankAccountID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBankAccountID(); ok {
		_spec.AddField(voucherorder.FieldBankAccountID, field.TypeInt, value)
	}
	if _u.mutation.BankAccountIDCleared() {
		_spec.ClearField(voucherorder.FieldBankAccountID, field.TypeInt)
	}
	if value, ok := _u.mutation.KvRetrieveReference(); ok {
		_spec.SetField(voucherorder.FieldKvRetrieveReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(voucherorder.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(voucherorder.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(voucherorder.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(voucherorder.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.FulfillError(); ok {
		_spec.SetField(voucherorder.FieldFulfillError, field.TypeString, value)
	}
	if _u.mutation.FulfillErrorCleared() {
		_spec.ClearField(voucherorder.FieldFulfillError, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(voucherorder.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(voucherorder.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(voucherorder.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FulfilledAt(); ok {
		_spec.SetField(voucherorder.FieldFulfilledAt, field.TypeTime, value)
	}
	if _u.mutation.FulfilledAtCleared() {
		_spec.ClearField(voucherorder.FieldFulfilledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(voucherorder.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(voucherorder.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(voucherorder.FieldClientIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(voucherorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voucherorder.UserTable,
			Columns: []string{voucherorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voucherorder.UserTable,
			Columns: []string{voucherorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voucherorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VoucherOrderUpdateOne is the builder for updating a single VoucherOrder entity.
type VoucherOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VoucherOrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *VoucherOrderUpdateOne) SetOrderNo(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableOrderNo(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VoucherOrderUpdateOne) SetUserID(v int64) *VoucherOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableUserID(v *int64) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *VoucherOrderUpdateOne) SetUserEmail(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableUserEmail(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *VoucherOrderUpdateOne) SetUserName(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableUserName(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *VoucherOrderUpdateOne) SetStatus(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableStatus(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *VoucherOrderUpdateOne) SetProductID(v int64) *VoucherOrderUpdateOne {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableProductID(v *int64) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *VoucherOrderUpdateOne) AddProductID(v int64) *VoucherOrderUpdateOne {
	_u.mutation.AddProductID(v)
	return _u
}

// SetKvProductID sets the "kv_product_id" field.
func (_u *VoucherOrderUpdateOne) SetKvProductID(v int64) *VoucherOrderUpdateOne {
	_u.mutation.ResetKvProductID()
	_u.mutation.SetKvProductID(v)
	return _u
}

// SetNillableKvProductID sets the "kv_product_id" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableKvProductID(v *int64) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetKvProductID(*v)
	}
	return _u
}

// AddKvProductID adds value to the "kv_product_id" field.
func (_u *VoucherOrderUpdateOne) AddKvProductID(v int64) *VoucherOrderUpdateOne {
	_u.mutation.AddKvProductID(v)
	return _u
}

// ClearKvProductID clears the value of the "kv_product_id" field.
func (_u *VoucherOrderUpdateOne) ClearKvProductID() *VoucherOrderUpdateOne {
	_u.mutation.ClearKvProductID()
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *VoucherOrderUpdateOne) SetProductName(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableProductName(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetDenomination sets the "denomination" field.
func (_u *VoucherOrderUpdateOne) SetDenomination(v float64) *VoucherOrderUpdateOne {
	_u.mutation.ResetDenomination()
	_u.mutation.SetDenomination(v)
	return _u
}

// SetNillableDenomination sets the "denomination" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableDenomination(v *float64) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetDenomination(*v)
	}
	return _u
}

// AddDenomination adds value to the "denomination" field.
func (_u *VoucherOrderUpdateOne) AddDenomination(v float64) *VoucherOrderUpdateOne {
	_u.mutation.AddDenomination(v)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *VoucherOrderUpdateOne) SetQuantity(v int) *VoucherOrderUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableQuantity(v *int) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *VoucherOrderUpdateOne) AddQuantity(v int) *VoucherOrderUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *VoucherOrderUpdateOne) SetUnitPrice(v float64) *VoucherOrderUpdateOne {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableUnitPrice(v *float64) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *VoucherOrderUpdateOne) AddUnitPrice(v float64) *VoucherOrderUpdateOne {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetSubtotal sets the "subtotal" field.
func (_u *VoucherOrderUpdateOne) SetSubtotal(v float64) *VoucherOrderUpdateOne {
	_u.mutation.ResetSubtotal()
	_u.mutation.SetSubtotal(v)
	return _u
}

// SetNillableSubtotal sets the "subtotal" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableSubtotal(v *float64) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetSubtotal(*v)
	}
	return _u
}

// AddSubtotal adds value to the "subtotal" field.
func (_u *VoucherOrderUpdateOne) AddSubtotal(v float64) *VoucherOrderUpdateOne {
	_u.mutation.AddSubtotal(v)
	return _u
}

// SetFeeAmount sets the "fee_amount" field.
func (_u *VoucherOrderUpdateOne) SetFeeAmount(v float64) *VoucherOrderUpdateOne {
	_u.mutation.ResetFeeAmount()
	_u.mutation.SetFeeAmount(v)
	return _u
}

// SetNillableFeeAmount sets the "fee_amount" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableFeeAmount(v *float64) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetFeeAmount(*v)
	}
	return _u
}

// AddFeeAmount adds value to the "fee_amount" field.
func (_u *VoucherOrderUpdateOne) AddFeeAmount(v float64) *VoucherOrderUpdateOne {
	_u.mutation.AddFeeAmount(v)
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *VoucherOrderUpdateOne) SetTotalAmount(v float64) *VoucherOrderUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableTotalAmount(v *float64) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *VoucherOrderUpdateOne) AddTotalAmount(v float64) *VoucherOrderUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *VoucherOrderUpdateOne) SetCurrency(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableCurrency(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetPaymentRef sets the "payment_ref" field.
func (_u *VoucherOrderUpdateOne) SetPaymentRef(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetPaymentRef(v)
	return _u
}

// SetNillablePaymentRef sets the "payment_ref" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillablePaymentRef(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetPaymentRef(*v)
	}
	return _u
}

// ClearPaymentRef clears the value of the "payment_ref" field.
func (_u *VoucherOrderUpdateOne) ClearPaymentRef() *VoucherOrderUpdateOne {
	_u.mutation.ClearPaymentRef()
	return _u
}

// SetPaymentProofPath sets the "payment_proof_path" field.
func (_u *VoucherOrderUpdateOne) SetPaymentProofPath(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetPaymentProofPath(v)
	return _u
}

// SetNillablePaymentProofPath sets the "payment_proof_path" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillablePaymentProofPath(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetPaymentProofPath(*v)
	}
	return _u
}

// ClearPaymentProofPath clears the value of the "payment_proof_path" field.
func (_u *VoucherOrderUpdateOne) ClearPaymentProofPath() *VoucherOrderUpdateOne {
	_u.mutation.ClearPaymentProofPath()
	return _u
}

// SetBankAccountID sets the "bank_account_id" field.
func (_u *VoucherOrderUpdateOne) SetBankAccountID(v int) *VoucherOrderUpdateOne {
	_u.mutation.ResetBankAccountID()
	_u.mutation.SetBankAccountID(v)
	return _u
}

// SetNillableBankAccountID sets the "bank_account_id" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableBankAccountID(v *int) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetBankAccountID(*v)
	}
	return _u
}

// AddBankAccountID adds value to the "bank_account_id" field.
func (_u *VoucherOrderUpdateOne) AddBankAccountID(v int) *VoucherOrderUpdateOne {
	_u.mutation.AddBankAccountID(v)
	return _u
}

// ClearBankAccountID clears the value of the "bank_account_id" field.
func (_u *VoucherOrderUpdateOne) ClearBankAccountID() *VoucherOrderUpdateOne {
	_u.mutation.ClearBankAccountID()
	return _u
}

// SetKvRetrieveReference sets the "kv_retrieve_reference" field.
func (_u *VoucherOrderUpdateOne) SetKvRetrieveReference(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetKvRetrieveReference(v)
	return _u
}

// SetNillableKvRetrieveReference sets the "kv_retrieve_reference" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableKvRetrieveReference(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetKvRetrieveReference(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *VoucherOrderUpdateOne) SetIdempotencyKey(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableIdempotencyKey(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *VoucherOrderUpdateOne) ClearIdempotencyKey() *VoucherOrderUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetRejectReason sets the "reject_reason" field.
func (_u *VoucherOrderUpdateOne) SetRejectReason(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetRejectReason(v)
	return _u
}

// SetNillableRejectReason sets the "reject_reason" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableRejectReason(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetRejectReason(*v)
	}
	return _u
}

// ClearRejectReason clears the value of the "reject_reason" field.
func (_u *VoucherOrderUpdateOne) ClearRejectReason() *VoucherOrderUpdateOne {
	_u.mutation.ClearRejectReason()
	return _u
}

// SetFulfillError sets the "fulfill_error" field.
func (_u *VoucherOrderUpdateOne) SetFulfillError(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetFulfillError(v)
	return _u
}

// SetNillableFulfillError sets the "fulfill_error" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableFulfillError(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetFulfillError(*v)
	}
	return _u
}

// ClearFulfillError clears the value of the "fulfill_error" field.
func (_u *VoucherOrderUpdateOne) ClearFulfillError() *VoucherOrderUpdateOne {
	_u.mutation.ClearFulfillError()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *VoucherOrderUpdateOne) SetExpiresAt(v time.Time) *VoucherOrderUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableExpiresAt(v *time.Time) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *VoucherOrderUpdateOne) SetVerifiedAt(v time.Time) *VoucherOrderUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableVerifiedAt(v *time.Time) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *VoucherOrderUpdateOne) ClearVerifiedAt() *VoucherOrderUpdateOne {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetFulfilledAt sets the "fulfilled_at" field.
func (_u *VoucherOrderUpdateOne) SetFulfilledAt(v time.Time) *VoucherOrderUpdateOne {
	_u.mutation.SetFulfilledAt(v)
	return _u
}

// SetNillableFulfilledAt sets the "fulfilled_at" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableFulfilledAt(v *time.Time) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetFulfilledAt(*v)
	}
	return _u
}

// ClearFulfilledAt clears the value of the "fulfilled_at" field.
func (_u *VoucherOrderUpdateOne) ClearFulfilledAt() *VoucherOrderUpdateOne {
	_u.mutation.ClearFulfilledAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *VoucherOrderUpdateOne) SetCompletedAt(v time.Time) *VoucherOrderUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableCompletedAt(v *time.Time) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *VoucherOrderUpdateOne) ClearCompletedAt() *VoucherOrderUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *VoucherOrderUpdateOne) SetClientIP(v string) *VoucherOrderUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *VoucherOrderUpdateOne) SetNillableClientIP(v *string) *VoucherOrderUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VoucherOrderUpdateOne) SetUpdatedAt(v time.Time) *VoucherOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VoucherOrderUpdateOne) SetUser(v *User) *VoucherOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the VoucherOrderMutation object of the builder.
func (_u *VoucherOrderUpdateOne) Mutation() *VoucherOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VoucherOrderUpdateOne) ClearUser() *VoucherOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the VoucherOrderUpdate builder.
func (_u *VoucherOrderUpdateOne) Where(ps ...predicate.VoucherOrder) *VoucherOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VoucherOrderUpdateOne) Select(field string, fields ...string) *VoucherOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VoucherOrder entity.
func (_u *VoucherOrderUpdateOne) Save(ctx context.Context) (*VoucherOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoucherOrderUpdateOne) SaveX(ctx context.Context) *VoucherOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VoucherOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoucherOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VoucherOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := voucherorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoucherOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := voucherorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserEmail(); ok {
		if err := voucherorder.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.user_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserName(); ok {
		if err := voucherorder.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.user_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := voucherorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := voucherorder.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := voucherorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentRef(); ok {
		if err := voucherorder.PaymentRefValidator(v); err != nil {
			return &ValidationError{Name: "payment_ref", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.payment_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentProofPath(); ok {
		if err := voucherorder.PaymentProofPathValidator(v); err != nil {
			return &ValidationError{Name: "payment_proof_path", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.payment_proof_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KvRetrieveReference(); ok {
		if err := voucherorder.KvRetrieveReferenceValidator(v); err != nil {
			return &ValidationError{Name: "kv_retrieve_reference", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.kv_retrieve_reference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := voucherorder.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := voucherorder.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "VoucherOrder.client_ip": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VoucherOrder.user"`)
	}
	return nil
}

func (_u *VoucherOrderUpdateOne) sqlSave(ctx context.Context) (_node *VoucherOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(voucherorder.Table, voucherorder.Columns, sqlgraph.NewFieldSpec(voucherorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VoucherOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, voucherorder.FieldID)
		for _, f := range fields {
			if !voucherorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != voucherorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(voucherorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(voucherorder.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(voucherorder.FieldUserName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(voucherorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(voucherorder.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(voucherorder.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.KvProductID(); ok {
		_spec.SetField(voucherorder.FieldKvProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedKvProductID(); ok {
		_spec.AddField(voucherorder.FieldKvProductID, field.TypeInt64, value)
	}
	if _u.mutation.KvProductIDCleared() {
		_spec.ClearField(voucherorder.FieldKvProductID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(voucherorder.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Denomination(); ok {
		_spec.SetField(voucherorder.FieldDenomination, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDenomination(); ok {
		_spec.AddField(voucherorder.FieldDenomination, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(voucherorder.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(voucherorder.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(voucherorder.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(voucherorder.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Subtotal(); ok {
		_spec.SetField(voucherorder.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSubtotal(); ok {
		_spec.AddField(voucherorder.FieldSubtotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FeeAmount(); ok {
		_spec.SetField(voucherorder.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFeeAmount(); ok {
		_spec.AddField(voucherorder.FieldFeeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(voucherorder.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(voucherorder.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(voucherorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentRef(); ok {
		_spec.SetField(voucherorder.FieldPaymentRef, field.TypeString, value)
	}
	if _u.mutation.PaymentRefCleared() {
		_spec.ClearField(voucherorder.FieldPaymentRef, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentProofPath(); ok {
		_spec.SetField(voucherorder.FieldPaymentProofPath, field.TypeString, value)
	}
	if _u.mutation.PaymentProofPathCleared() {
		_spec.ClearField(voucherorder.FieldPaymentProofPath, field.TypeString)
	}
	if value, ok := _u.mutation.BankAccountID(); ok {
		_spec.SetField(voucherorder.FieldBankAccountID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBankAccountID(); ok {
		_spec.AddField(voucherorder.FieldBankAccountID, field.TypeInt, value)
	}
	if _u.mutation.BankAccountIDCleared() {
		_spec.ClearField(voucherorder.FieldBankAccountID, field.TypeInt)
	}
	if value, ok := _u.mutation.KvRetrieveReference(); ok {
		_spec.SetField(voucherorder.FieldKvRetrieveReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(voucherorder.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(voucherorder.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.RejectReason(); ok {
		_spec.SetField(voucherorder.FieldRejectReason, field.TypeString, value)
	}
	if _u.mutation.RejectReasonCleared() {
		_spec.ClearField(voucherorder.FieldRejectReason, field.TypeString)
	}
	if value, ok := _u.mutation.FulfillError(); ok {
		_spec.SetField(voucherorder.FieldFulfillError, field.TypeString, value)
	}
	if _u.mutation.FulfillErrorCleared() {
		_spec.ClearField(voucherorder.FieldFulfillError, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(voucherorder.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(voucherorder.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(voucherorder.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FulfilledAt(); ok {
		_spec.SetField(voucherorder.FieldFulfilledAt, field.TypeTime, value)
	}
	if _u.mutation.FulfilledAtCleared() {
		_spec.ClearField(voucherorder.FieldFulfilledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(voucherorder.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(voucherorder.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(voucherorder.FieldClientIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(voucherorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voucherorder.UserTable,
			Columns: []string{voucherorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   voucherorder.UserTable,
			Columns: []string{voucherorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VoucherOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voucherorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
