// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/voucherpindelivery"
)

// VoucherPinDeliveryDelete is the builder for deleting a VoucherPinDelivery entity.
type VoucherPinDeliveryDelete struct {
	config
	hooks    []Hook
	mutation *VoucherPinDeliveryMutation
}

// Where appends a list predicates to the VoucherPinDeliveryDelete builder.
func (_d *VoucherPinDeliveryDelete) Where(ps ...predicate.VoucherPinDelivery) *VoucherPinDeliveryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *VoucherPinDeliveryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VoucherPinDeliveryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *VoucherPinDeliveryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(voucherpindelivery.Table, sqlgraph.NewFieldSpec(voucherpindelivery.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// VoucherPinDeliveryDeleteOne is the builder for deleting a single VoucherPinDelivery entity.
type VoucherPinDeliveryDeleteOne struct {
	_d *VoucherPinDeliveryDelete
}

// Where appends a list predicates to the VoucherPinDeliveryDelete builder.
func (_d *VoucherPinDeliveryDeleteOne) Where(ps ...predicate.VoucherPinDelivery) *VoucherPinDeliveryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *VoucherPinDeliveryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{voucherpindelivery.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VoucherPinDeliveryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
