// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/voucherproduct"
)

// VoucherProduct is the model entity for the VoucherProduct schema.
type VoucherProduct struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// KvProductID holds the value of the "kv_product_id" field.
	KvProductID *int64 `json:"kv_product_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Denomination holds the value of the "denomination" field.
	Denomination float64 `json:"denomination,omitempty"`
	// WholesalePrice holds the value of the "wholesale_price" field.
	WholesalePrice float64 `json:"wholesale_price,omitempty"`
	// RetailPrice holds the value of the "retail_price" field.
	RetailPrice float64 `json:"retail_price,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// StockAvailable holds the value of the "stock_available" field.
	StockAvailable int `json:"stock_available,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VoucherProduct) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case voucherproduct.FieldIsActive:
			values[i] = new(sql.NullBool)
		case voucherproduct.FieldDenomination, voucherproduct.FieldWholesalePrice, voucherproduct.FieldRetailPrice:
			values[i] = new(sql.NullFloat64)
		case voucherproduct.FieldID, voucherproduct.FieldKvProductID, voucherproduct.FieldStockAvailable, voucherproduct.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case voucherproduct.FieldName, voucherproduct.FieldCurrency:
			values[i] = new(sql.NullString)
		case voucherproduct.FieldCreatedAt, voucherproduct.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VoucherProduct fields.
func (_m *VoucherProduct) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case voucherproduct.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case voucherproduct.FieldKvProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field kv_product_id", values[i])
			} else if value.Valid {
				_m.KvProductID = new(int64)
				*_m.KvProductID = value.Int64
			}
		case voucherproduct.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case voucherproduct.FieldDenomination:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field denomination", values[i])
			} else if value.Valid {
				_m.Denomination = value.Float64
			}
		case voucherproduct.FieldWholesalePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field wholesale_price", values[i])
			} else if value.Valid {
				_m.WholesalePrice = value.Float64
			}
		case voucherproduct.FieldRetailPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field retail_price", values[i])
			} else if value.Valid {
				_m.RetailPrice = value.Float64
			}
		case voucherproduct.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case voucherproduct.FieldStockAvailable:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stock_available", values[i])
			} else if value.Valid {
				_m.StockAvailable = int(value.Int64)
			}
		case voucherproduct.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case voucherproduct.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case voucherproduct.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case voucherproduct.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VoucherProduct.
// This includes values selected through modifiers, order, etc.
func (_m *VoucherProduct) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VoucherProduct.
// Note that you need to call VoucherProduct.Unwrap() before calling this method if this VoucherProduct
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VoucherProduct) Update() *VoucherProductUpdateOne {
	return NewVoucherProductClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VoucherProduct entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VoucherProduct) Unwrap() *VoucherProduct {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VoucherProduct is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VoucherProduct) String() string {
	var builder strings.Builder
	builder.WriteString("VoucherProduct(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.KvProductID; v != nil {
		builder.WriteString("kv_product_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("denomination=")
	builder.WriteString(fmt.Sprintf("%v", _m.Denomination))
	builder.WriteString(", ")
	builder.WriteString("wholesale_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.WholesalePrice))
	builder.WriteString(", ")
	builder.WriteString("retail_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetailPrice))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("stock_available=")
	builder.WriteString(fmt.Sprintf("%v", _m.StockAvailable))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VoucherProducts is a parsable slice of VoucherProduct.
type VoucherProducts []*VoucherProduct
