// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/voucherpindelivery"
)

// VoucherPinDeliveryUpdate is the builder for updating VoucherPinDelivery entities.
type VoucherPinDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *VoucherPinDeliveryMutation
}

// Where appends a list predicates to the VoucherPinDeliveryUpdate builder.
func (_u *VoucherPinDeliveryUpdate) Where(ps ...predicate.VoucherPinDelivery) *VoucherPinDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *VoucherPinDeliveryUpdate) SetOrderID(v int64) *VoucherPinDeliveryUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdate) SetNillableOrderID(v *int64) *VoucherPinDeliveryUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *VoucherPinDeliveryUpdate) AddOrderID(v int64) *VoucherPinDeliveryUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetPinCodeEnc sets the "pin_code_enc" field.
func (_u *VoucherPinDeliveryUpdate) SetPinCodeEnc(v string) *VoucherPinDeliveryUpdate {
	_u.mutation.SetPinCodeEnc(v)
	return _u
}

// SetNillablePinCodeEnc sets the "pin_code_enc" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdate) SetNillablePinCodeEnc(v *string) *VoucherPinDeliveryUpdate {
	if v != nil {
		_u.SetPinCodeEnc(*v)
	}
	return _u
}

// SetSerial sets the "serial" field.
func (_u *VoucherPinDeliveryUpdate) SetSerial(v string) *VoucherPinDeliveryUpdate {
	_u.mutation.SetSerial(v)
	return _u
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdate) SetNillableSerial(v *string) *VoucherPinDeliveryUpdate {
	if v != nil {
		_u.SetSerial(*v)
	}
	return _u
}

// SetDenomination sets the "denomination" field.
func (_u *VoucherPinDeliveryUpdate) SetDenomination(v float64) *VoucherPinDeliveryUpdate {
	_u.mutation.ResetDenomination()
	_u.mutation.SetDenomination(v)
	return _u
}

// SetNillableDenomination sets the "denomination" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdate) SetNillableDenomination(v *float64) *VoucherPinDeliveryUpdate {
	if v != nil {
		_u.SetDenomination(*v)
	}
	return _u
}

// AddDenomination adds value to the "denomination" field.
func (_u *VoucherPinDeliveryUpdate) AddDenomination(v float64) *VoucherPinDeliveryUpdate {
	_u.mutation.AddDenomination(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *VoucherPinDeliveryUpdate) SetExpiresAt(v time.Time) *VoucherPinDeliveryUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdate) SetNillableExpiresAt(v *time.Time) *VoucherPinDeliveryUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *VoucherPinDeliveryUpdate) ClearExpiresAt() *VoucherPinDeliveryUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *VoucherPinDeliveryUpdate) SetDeliveredAt(v time.Time) *VoucherPinDeliveryUpdate {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdate) SetNillableDeliveredAt(v *time.Time) *VoucherPinDeliveryUpdate {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// Mutation returns the VoucherPinDeliveryMutation object of the builder.
func (_u *VoucherPinDeliveryUpdate) Mutation() *VoucherPinDeliveryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VoucherPinDeliveryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoucherPinDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VoucherPinDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoucherPinDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoucherPinDeliveryUpdate) check() error {
	if v, ok := _u.mutation.Serial(); ok {
		if err := voucherpindelivery.SerialValidator(v); err != nil {
			return &ValidationError{Name: "serial", err: fmt.Errorf(`ent: validator failed for field "VoucherPinDelivery.serial": %w`, err)}
		}
	}
	return nil
}

func (_u *VoucherPinDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(voucherpindelivery.Table, voucherpindelivery.Columns, sqlgraph.NewFieldSpec(voucherpindelivery.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(voucherpindelivery.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(voucherpindelivery.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PinCodeEnc(); ok {
		_spec.SetField(voucherpindelivery.FieldPinCodeEnc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Serial(); ok {
		_spec.SetField(voucherpindelivery.FieldSerial, field.TypeString, value)
	}
	if value, ok := _u.mutation.Denomination(); ok {
		_spec.SetField(voucherpindelivery.FieldDenomination, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDenomination(); ok {
		_spec.AddField(voucherpindelivery.FieldDenomination, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(voucherpindelivery.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(voucherpindelivery.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(voucherpindelivery.FieldDeliveredAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voucherpindelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VoucherPinDeliveryUpdateOne is the builder for updating a single VoucherPinDelivery entity.
type VoucherPinDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VoucherPinDeliveryMutation
}

// SetOrderID sets the "order_id" field.
func (_u *VoucherPinDeliveryUpdateOne) SetOrderID(v int64) *VoucherPinDeliveryUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdateOne) SetNillableOrderID(v *int64) *VoucherPinDeliveryUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *VoucherPinDeliveryUpdateOne) AddOrderID(v int64) *VoucherPinDeliveryUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetPinCodeEnc sets the "pin_code_enc" field.
func (_u *VoucherPinDeliveryUpdateOne) SetPinCodeEnc(v string) *VoucherPinDeliveryUpdateOne {
	_u.mutation.SetPinCodeEnc(v)
	return _u
}

// SetNillablePinCodeEnc sets the "pin_code_enc" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdateOne) SetNillablePinCodeEnc(v *string) *VoucherPinDeliveryUpdateOne {
	if v != nil {
		_u.SetPinCodeEnc(*v)
	}
	return _u
}

// SetSerial sets the "serial" field.
func (_u *VoucherPinDeliveryUpdateOne) SetSerial(v string) *VoucherPinDeliveryUpdateOne {
	_u.mutation.SetSerial(v)
	return _u
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdateOne) SetNillableSerial(v *string) *VoucherPinDeliveryUpdateOne {
	if v != nil {
		_u.SetSerial(*v)
	}
	return _u
}

// SetDenomination sets the "denomination" field.
func (_u *VoucherPinDeliveryUpdateOne) SetDenomination(v float64) *VoucherPinDeliveryUpdateOne {
	_u.mutation.ResetDenomination()
	_u.mutation.SetDenomination(v)
	return _u
}

// SetNillableDenomination sets the "denomination" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdateOne) SetNillableDenomination(v *float64) *VoucherPinDeliveryUpdateOne {
	if v != nil {
		_u.SetDenomination(*v)
	}
	return _u
}

// AddDenomination adds value to the "denomination" field.
func (_u *VoucherPinDeliveryUpdateOne) AddDenomination(v float64) *VoucherPinDeliveryUpdateOne {
	_u.mutation.AddDenomination(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *VoucherPinDeliveryUpdateOne) SetExpiresAt(v time.Time) *VoucherPinDeliveryUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdateOne) SetNillableExpiresAt(v *time.Time) *VoucherPinDeliveryUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *VoucherPinDeliveryUpdateOne) ClearExpiresAt() *VoucherPinDeliveryUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *VoucherPinDeliveryUpdateOne) SetDeliveredAt(v time.Time) *VoucherPinDeliveryUpdateOne {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *VoucherPinDeliveryUpdateOne) SetNillableDeliveredAt(v *time.Time) *VoucherPinDeliveryUpdateOne {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// Mutation returns the VoucherPinDeliveryMutation object of the builder.
func (_u *VoucherPinDeliveryUpdateOne) Mutation() *VoucherPinDeliveryMutation {
	return _u.mutation
}

// Where appends a list predicates to the VoucherPinDeliveryUpdate builder.
func (_u *VoucherPinDeliveryUpdateOne) Where(ps ...predicate.VoucherPinDelivery) *VoucherPinDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VoucherPinDeliveryUpdateOne) Select(field string, fields ...string) *VoucherPinDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VoucherPinDelivery entity.
func (_u *VoucherPinDeliveryUpdateOne) Save(ctx context.Context) (*VoucherPinDelivery, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VoucherPinDeliveryUpdateOne) SaveX(ctx context.Context) *VoucherPinDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VoucherPinDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VoucherPinDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VoucherPinDeliveryUpdateOne) check() error {
	if v, ok := _u.mutation.Serial(); ok {
		if err := voucherpindelivery.SerialValidator(v); err != nil {
			return &ValidationError{Name: "serial", err: fmt.Errorf(`ent: validator failed for field "VoucherPinDelivery.serial": %w`, err)}
		}
	}
	return nil
}

func (_u *VoucherPinDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *VoucherPinDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(voucherpindelivery.Table, voucherpindelivery.Columns, sqlgraph.NewFieldSpec(voucherpindelivery.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VoucherPinDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, voucherpindelivery.FieldID)
		for _, f := range fields {
			if !voucherpindelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != voucherpindelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(voucherpindelivery.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(voucherpindelivery.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PinCodeEnc(); ok {
		_spec.SetField(voucherpindelivery.FieldPinCodeEnc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Serial(); ok {
		_spec.SetField(voucherpindelivery.FieldSerial, field.TypeString, value)
	}
	if value, ok := _u.mutation.Denomination(); ok {
		_spec.SetField(voucherpindelivery.FieldDenomination, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDenomination(); ok {
		_spec.AddField(voucherpindelivery.FieldDenomination, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(voucherpindelivery.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(voucherpindelivery.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(voucherpindelivery.FieldDeliveredAt, field.TypeTime, value)
	}
	_node = &VoucherPinDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voucherpindelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
