// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/voucherb2border"
)

// VoucherB2BOrderDelete is the builder for deleting a VoucherB2BOrder entity.
type VoucherB2BOrderDelete struct {
	config
	hooks    []Hook
	mutation *VoucherB2BOrderMutation
}

// Where appends a list predicates to the VoucherB2BOrderDelete builder.
func (_d *VoucherB2BOrderDelete) Where(ps ...predicate.VoucherB2BOrder) *VoucherB2BOrderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *VoucherB2BOrderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VoucherB2BOrderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *VoucherB2BOrderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(voucherb2border.Table, sqlgraph.NewFieldSpec(voucherb2border.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// VoucherB2BOrderDeleteOne is the builder for deleting a single VoucherB2BOrder entity.
type VoucherB2BOrderDeleteOne struct {
	_d *VoucherB2BOrderDelete
}

// Where appends a list predicates to the VoucherB2BOrderDelete builder.
func (_d *VoucherB2BOrderDeleteOne) Where(ps ...predicate.VoucherB2BOrder) *VoucherB2BOrderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *VoucherB2BOrderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{voucherb2border.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VoucherB2BOrderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
