// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/voucherpindelivery"
)

// VoucherPinDeliveryCreate is the builder for creating a VoucherPinDelivery entity.
type VoucherPinDeliveryCreate struct {
	config
	mutation *VoucherPinDeliveryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderID sets the "order_id" field.
func (_c *VoucherPinDeliveryCreate) SetOrderID(v int64) *VoucherPinDeliveryCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetPinCodeEnc sets the "pin_code_enc" field.
func (_c *VoucherPinDeliveryCreate) SetPinCodeEnc(v string) *VoucherPinDeliveryCreate {
	_c.mutation.SetPinCodeEnc(v)
	return _c
}

// SetSerial sets the "serial" field.
func (_c *VoucherPinDeliveryCreate) SetSerial(v string) *VoucherPinDeliveryCreate {
	_c.mutation.SetSerial(v)
	return _c
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_c *VoucherPinDeliveryCreate) SetNillableSerial(v *string) *VoucherPinDeliveryCreate {
	if v != nil {
		_c.SetSerial(*v)
	}
	return _c
}

// SetDenomination sets the "denomination" field.
func (_c *VoucherPinDeliveryCreate) SetDenomination(v float64) *VoucherPinDeliveryCreate {
	_c.mutation.SetDenomination(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *VoucherPinDeliveryCreate) SetExpiresAt(v time.Time) *VoucherPinDeliveryCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *VoucherPinDeliveryCreate) SetNillableExpiresAt(v *time.Time) *VoucherPinDeliveryCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetDeliveredAt sets the "delivered_at" field.
func (_c *VoucherPinDeliveryCreate) SetDeliveredAt(v time.Time) *VoucherPinDeliveryCreate {
	_c.mutation.SetDeliveredAt(v)
	return _c
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_c *VoucherPinDeliveryCreate) SetNillableDeliveredAt(v *time.Time) *VoucherPinDeliveryCreate {
	if v != nil {
		_c.SetDeliveredAt(*v)
	}
	return _c
}

// Mutation returns the VoucherPinDeliveryMutation object of the builder.
func (_c *VoucherPinDeliveryCreate) Mutation() *VoucherPinDeliveryMutation {
	return _c.mutation
}

// Save creates the VoucherPinDelivery in the database.
func (_c *VoucherPinDeliveryCreate) Save(ctx context.Context) (*VoucherPinDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VoucherPinDeliveryCreate) SaveX(ctx context.Context) *VoucherPinDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoucherPinDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoucherPinDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VoucherPinDeliveryCreate) defaults() {
	if _, ok := _c.mutation.Serial(); !ok {
		v := voucherpindelivery.DefaultSerial
		_c.mutation.SetSerial(v)
	}
	if _, ok := _c.mutation.DeliveredAt(); !ok {
		v := voucherpindelivery.DefaultDeliveredAt()
		_c.mutation.SetDeliveredAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VoucherPinDeliveryCreate) check() error {
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "VoucherPinDelivery.order_id"`)}
	}
	if _, ok := _c.mutation.PinCodeEnc(); !ok {
		return &ValidationError{Name: "pin_code_enc", err: errors.New(`ent: missing required field "VoucherPinDelivery.pin_code_enc"`)}
	}
	if _, ok := _c.mutation.Serial(); !ok {
		return &ValidationError{Name: "serial", err: errors.New(`ent: missing required field "VoucherPinDelivery.serial"`)}
	}
	if v, ok := _c.mutation.Serial(); ok {
		if err := voucherpindelivery.SerialValidator(v); err != nil {
			return &ValidationError{Name: "serial", err: fmt.Errorf(`ent: validator failed for field "VoucherPinDelivery.serial": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Denomination(); !ok {
		return &ValidationError{Name: "denomination", err: errors.New(`ent: missing required field "VoucherPinDelivery.denomination"`)}
	}
	if _, ok := _c.mutation.DeliveredAt(); !ok {
		return &ValidationError{Name: "delivered_at", err: errors.New(`ent: missing required field "VoucherPinDelivery.delivered_at"`)}
	}
	return nil
}

func (_c *VoucherPinDeliveryCreate) sqlSave(ctx context.Context) (*VoucherPinDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VoucherPinDeliveryCreate) createSpec() (*VoucherPinDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &VoucherPinDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(voucherpindelivery.Table, sqlgraph.NewFieldSpec(voucherpindelivery.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(voucherpindelivery.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.PinCodeEnc(); ok {
		_spec.SetField(voucherpindelivery.FieldPinCodeEnc, field.TypeString, value)
		_node.PinCodeEnc = value
	}
	if value, ok := _c.mutation.Serial(); ok {
		_spec.SetField(voucherpindelivery.FieldSerial, field.TypeString, value)
		_node.Serial = value
	}
	if value, ok := _c.mutation.Denomination(); ok {
		_spec.SetField(voucherpindelivery.FieldDenomination, field.TypeFloat64, value)
		_node.Denomination = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(voucherpindelivery.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.DeliveredAt(); ok {
		_spec.SetField(voucherpindelivery.FieldDeliveredAt, field.TypeTime, value)
		_node.DeliveredAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VoucherPinDelivery.Create().
//		SetOrderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VoucherPinDeliveryUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *VoucherPinDeliveryCreate) OnConflict(opts ...sql.ConflictOption) *VoucherPinDeliveryUpsertOne {
	_c.conflict = opts
	return &VoucherPinDeliveryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VoucherPinDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VoucherPinDeliveryCreate) OnConflictColumns(columns ...string) *VoucherPinDeliveryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VoucherPinDeliveryUpsertOne{
		create: _c,
	}
}

type (
	// VoucherPinDeliveryUpsertOne is the builder for "upsert"-ing
	//  one VoucherPinDelivery node.
	VoucherPinDeliveryUpsertOne struct {
		create *VoucherPinDeliveryCreate
	}

	// VoucherPinDeliveryUpsert is the "OnConflict" setter.
	VoucherPinDeliveryUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderID sets the "order_id" field.
func (u *VoucherPinDeliveryUpsert) SetOrderID(v int64) *VoucherPinDeliveryUpsert {
	u.Set(voucherpindelivery.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsert) UpdateOrderID() *VoucherPinDeliveryUpsert {
	u.SetExcluded(voucherpindelivery.FieldOrderID)
	return u
}

// AddOrderID adds v to the "order_id" field.
func (u *VoucherPinDeliveryUpsert) AddOrderID(v int64) *VoucherPinDeliveryUpsert {
	u.Add(voucherpindelivery.FieldOrderID, v)
	return u
}

// SetPinCodeEnc sets the "pin_code_enc" field.
func (u *VoucherPinDeliveryUpsert) SetPinCodeEnc(v string) *VoucherPinDeliveryUpsert {
	u.Set(voucherpindelivery.FieldPinCodeEnc, v)
	return u
}

// UpdatePinCodeEnc sets the "pin_code_enc" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsert) UpdatePinCodeEnc() *VoucherPinDeliveryUpsert {
	u.SetExcluded(voucherpindelivery.FieldPinCodeEnc)
	return u
}

// SetSerial sets the "serial" field.
func (u *VoucherPinDeliveryUpsert) SetSerial(v string) *VoucherPinDeliveryUpsert {
	u.Set(voucherpindelivery.FieldSerial, v)
	return u
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsert) UpdateSerial() *VoucherPinDeliveryUpsert {
	u.SetExcluded(voucherpindelivery.FieldSerial)
	return u
}

// SetDenomination sets the "denomination" field.
func (u *VoucherPinDeliveryUpsert) SetDenomination(v float64) *VoucherPinDeliveryUpsert {
	u.Set(voucherpindelivery.FieldDenomination, v)
	return u
}

// UpdateDenomination sets the "denomination" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsert) UpdateDenomination() *VoucherPinDeliveryUpsert {
	u.SetExcluded(voucherpindelivery.FieldDenomination)
	return u
}

// AddDenomination adds v to the "denomination" field.
func (u *VoucherPinDeliveryUpsert) AddDenomination(v float64) *VoucherPinDeliveryUpsert {
	u.Add(voucherpindelivery.FieldDenomination, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *VoucherPinDeliveryUpsert) SetExpiresAt(v time.Time) *VoucherPinDeliveryUpsert {
	u.Set(voucherpindelivery.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsert) UpdateExpiresAt() *VoucherPinDeliveryUpsert {
	u.SetExcluded(voucherpindelivery.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *VoucherPinDeliveryUpsert) ClearExpiresAt() *VoucherPinDeliveryUpsert {
	u.SetNull(voucherpindelivery.FieldExpiresAt)
	return u
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *VoucherPinDeliveryUpsert) SetDeliveredAt(v time.Time) *VoucherPinDeliveryUpsert {
	u.Set(voucherpindelivery.FieldDeliveredAt, v)
	return u
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsert) UpdateDeliveredAt() *VoucherPinDeliveryUpsert {
	u.SetExcluded(voucherpindelivery.FieldDeliveredAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VoucherPinDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VoucherPinDeliveryUpsertOne) UpdateNewValues() *VoucherPinDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VoucherPinDelivery.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VoucherPinDeliveryUpsertOne) Ignore() *VoucherPinDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VoucherPinDeliveryUpsertOne) DoNothing() *VoucherPinDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VoucherPinDeliveryCreate.OnConflict
// documentation for more info.
func (u *VoucherPinDeliveryUpsertOne) Update(set func(*VoucherPinDeliveryUpsert)) *VoucherPinDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VoucherPinDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *VoucherPinDeliveryUpsertOne) SetOrderID(v int64) *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *VoucherPinDeliveryUpsertOne) AddOrderID(v int64) *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertOne) UpdateOrderID() *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateOrderID()
	})
}

// SetPinCodeEnc sets the "pin_code_enc" field.
func (u *VoucherPinDeliveryUpsertOne) SetPinCodeEnc(v string) *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetPinCodeEnc(v)
	})
}

// UpdatePinCodeEnc sets the "pin_code_enc" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertOne) UpdatePinCodeEnc() *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdatePinCodeEnc()
	})
}

// SetSerial sets the "serial" field.
func (u *VoucherPinDeliveryUpsertOne) SetSerial(v string) *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertOne) UpdateSerial() *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateSerial()
	})
}

// SetDenomination sets the "denomination" field.
func (u *VoucherPinDeliveryUpsertOne) SetDenomination(v float64) *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetDenomination(v)
	})
}

// AddDenomination adds v to the "denomination" field.
func (u *VoucherPinDeliveryUpsertOne) AddDenomination(v float64) *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.AddDenomination(v)
	})
}

// UpdateDenomination sets the "denomination" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertOne) UpdateDenomination() *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateDenomination()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *VoucherPinDeliveryUpsertOne) SetExpiresAt(v time.Time) *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertOne) UpdateExpiresAt() *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *VoucherPinDeliveryUpsertOne) ClearExpiresAt() *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.ClearExpiresAt()
	})
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *VoucherPinDeliveryUpsertOne) SetDeliveredAt(v time.Time) *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetDeliveredAt(v)
	})
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertOne) UpdateDeliveredAt() *VoucherPinDeliveryUpsertOne {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateDeliveredAt()
	})
}

// Exec executes the query.
func (u *VoucherPinDeliveryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VoucherPinDeliveryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VoucherPinDeliveryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VoucherPinDeliveryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VoucherPinDeliveryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VoucherPinDeliveryCreateBulk is the builder for creating many VoucherPinDelivery entities in bulk.
type VoucherPinDeliveryCreateBulk struct {
	config
	err      error
	builders []*VoucherPinDeliveryCreate
	conflict []sql.ConflictOption
}

// Save creates the VoucherPinDelivery entities in the database.
func (_c *VoucherPinDeliveryCreateBulk) Save(ctx context.Context) ([]*VoucherPinDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VoucherPinDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VoucherPinDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VoucherPinDeliveryCreateBulk) SaveX(ctx context.Context) []*VoucherPinDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoucherPinDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoucherPinDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VoucherPinDelivery.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VoucherPinDeliveryUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *VoucherPinDeliveryCreateBulk) OnConflict(opts ...sql.ConflictOption) *VoucherPinDeliveryUpsertBulk {
	_c.conflict = opts
	return &VoucherPinDeliveryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VoucherPinDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VoucherPinDeliveryCreateBulk) OnConflictColumns(columns ...string) *VoucherPinDeliveryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VoucherPinDeliveryUpsertBulk{
		create: _c,
	}
}

// VoucherPinDeliveryUpsertBulk is the builder for "upsert"-ing
// a bulk of VoucherPinDelivery nodes.
type VoucherPinDeliveryUpsertBulk struct {
	create *VoucherPinDeliveryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VoucherPinDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VoucherPinDeliveryUpsertBulk) UpdateNewValues() *VoucherPinDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VoucherPinDelivery.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VoucherPinDeliveryUpsertBulk) Ignore() *VoucherPinDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VoucherPinDeliveryUpsertBulk) DoNothing() *VoucherPinDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VoucherPinDeliveryCreateBulk.OnConflict
// documentation for more info.
func (u *VoucherPinDeliveryUpsertBulk) Update(set func(*VoucherPinDeliveryUpsert)) *VoucherPinDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VoucherPinDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *VoucherPinDeliveryUpsertBulk) SetOrderID(v int64) *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *VoucherPinDeliveryUpsertBulk) AddOrderID(v int64) *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertBulk) UpdateOrderID() *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateOrderID()
	})
}

// SetPinCodeEnc sets the "pin_code_enc" field.
func (u *VoucherPinDeliveryUpsertBulk) SetPinCodeEnc(v string) *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetPinCodeEnc(v)
	})
}

// UpdatePinCodeEnc sets the "pin_code_enc" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertBulk) UpdatePinCodeEnc() *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdatePinCodeEnc()
	})
}

// SetSerial sets the "serial" field.
func (u *VoucherPinDeliveryUpsertBulk) SetSerial(v string) *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetSerial(v)
	})
}

// UpdateSerial sets the "serial" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertBulk) UpdateSerial() *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateSerial()
	})
}

// SetDenomination sets the "denomination" field.
func (u *VoucherPinDeliveryUpsertBulk) SetDenomination(v float64) *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetDenomination(v)
	})
}

// AddDenomination adds v to the "denomination" field.
func (u *VoucherPinDeliveryUpsertBulk) AddDenomination(v float64) *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.AddDenomination(v)
	})
}

// UpdateDenomination sets the "denomination" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertBulk) UpdateDenomination() *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateDenomination()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *VoucherPinDeliveryUpsertBulk) SetExpiresAt(v time.Time) *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertBulk) UpdateExpiresAt() *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *VoucherPinDeliveryUpsertBulk) ClearExpiresAt() *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.ClearExpiresAt()
	})
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *VoucherPinDeliveryUpsertBulk) SetDeliveredAt(v time.Time) *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.SetDeliveredAt(v)
	})
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *VoucherPinDeliveryUpsertBulk) UpdateDeliveredAt() *VoucherPinDeliveryUpsertBulk {
	return u.Update(func(s *VoucherPinDeliveryUpsert) {
		s.UpdateDeliveredAt()
	})
}

// Exec executes the query.
func (u *VoucherPinDeliveryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VoucherPinDeliveryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VoucherPinDeliveryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VoucherPinDeliveryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
