// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/voucherproduct"
)

// VoucherProductCreate is the builder for creating a VoucherProduct entity.
type VoucherProductCreate struct {
	config
	mutation *VoucherProductMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKvProductID sets the "kv_product_id" field.
func (_c *VoucherProductCreate) SetKvProductID(v int64) *VoucherProductCreate {
	_c.mutation.SetKvProductID(v)
	return _c
}

// SetNillableKvProductID sets the "kv_product_id" field if the given value is not nil.
func (_c *VoucherProductCreate) SetNillableKvProductID(v *int64) *VoucherProductCreate {
	if v != nil {
		_c.SetKvProductID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *VoucherProductCreate) SetName(v string) *VoucherProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDenomination sets the "denomination" field.
func (_c *VoucherProductCreate) SetDenomination(v float64) *VoucherProductCreate {
	_c.mutation.SetDenomination(v)
	return _c
}

// SetWholesalePrice sets the "wholesale_price" field.
func (_c *VoucherProductCreate) SetWholesalePrice(v float64) *VoucherProductCreate {
	_c.mutation.SetWholesalePrice(v)
	return _c
}

// SetNillableWholesalePrice sets the "wholesale_price" field if the given value is not nil.
func (_c *VoucherProductCreate) SetNillableWholesalePrice(v *float64) *VoucherProductCreate {
	if v != nil {
		_c.SetWholesalePrice(*v)
	}
	return _c
}

// SetRetailPrice sets the "retail_price" field.
func (_c *VoucherProductCreate) SetRetailPrice(v float64) *VoucherProductCreate {
	_c.mutation.SetRetailPrice(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *VoucherProductCreate) SetCurrency(v string) *VoucherProductCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *VoucherProductCreate) SetNillableCurrency(v *string) *VoucherProductCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetStockAvailable sets the "stock_available" field.
func (_c *VoucherProductCreate) SetStockAvailable(v int) *VoucherProductCreate {
	_c.mutation.SetStockAvailable(v)
	return _c
}

// SetNillableStockAvailable sets the "stock_available" field if the given value is not nil.
func (_c *VoucherProductCreate) SetNillableStockAvailable(v *int) *VoucherProductCreate {
	if v != nil {
		_c.SetStockAvailable(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *VoucherProductCreate) SetIsActive(v bool) *VoucherProductCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *VoucherProductCreate) SetNillableIsActive(v *bool) *VoucherProductCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *VoucherProductCreate) SetSortOrder(v int) *VoucherProductCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *VoucherProductCreate) SetNillableSortOrder(v *int) *VoucherProductCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VoucherProductCreate) SetCreatedAt(v time.Time) *VoucherProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VoucherProductCreate) SetNillableCreatedAt(v *time.Time) *VoucherProductCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VoucherProductCreate) SetUpdatedAt(v time.Time) *VoucherProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VoucherProductCreate) SetNillableUpdatedAt(v *time.Time) *VoucherProductCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the VoucherProductMutation object of the builder.
func (_c *VoucherProductCreate) Mutation() *VoucherProductMutation {
	return _c.mutation
}

// Save creates the VoucherProduct in the database.
func (_c *VoucherProductCreate) Save(ctx context.Context) (*VoucherProduct, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VoucherProductCreate) SaveX(ctx context.Context) *VoucherProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoucherProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoucherProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VoucherProductCreate) defaults() {
	if _, ok := _c.mutation.WholesalePrice(); !ok {
		v := voucherproduct.DefaultWholesalePrice
		_c.mutation.SetWholesalePrice(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := voucherproduct.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.StockAvailable(); !ok {
		v := voucherproduct.DefaultStockAvailable
		_c.mutation.SetStockAvailable(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := voucherproduct.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := voucherproduct.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := voucherproduct.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := voucherproduct.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VoucherProductCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "VoucherProduct.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := voucherproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VoucherProduct.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Denomination(); !ok {
		return &ValidationError{Name: "denomination", err: errors.New(`ent: missing required field "VoucherProduct.denomination"`)}
	}
	if _, ok := _c.mutation.WholesalePrice(); !ok {
		return &ValidationError{Name: "wholesale_price", err: errors.New(`ent: missing required field "VoucherProduct.wholesale_price"`)}
	}
	if _, ok := _c.mutation.RetailPrice(); !ok {
		return &ValidationError{Name: "retail_price", err: errors.New(`ent: missing required field "VoucherProduct.retail_price"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "VoucherProduct.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := voucherproduct.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "VoucherProduct.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StockAvailable(); !ok {
		return &ValidationError{Name: "stock_available", err: errors.New(`ent: missing required field "VoucherProduct.stock_available"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "VoucherProduct.is_active"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "VoucherProduct.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VoucherProduct.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VoucherProduct.updated_at"`)}
	}
	return nil
}

func (_c *VoucherProductCreate) sqlSave(ctx context.Context) (*VoucherProduct, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VoucherProductCreate) createSpec() (*VoucherProduct, *sqlgraph.CreateSpec) {
	var (
		_node = &VoucherProduct{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(voucherproduct.Table, sqlgraph.NewFieldSpec(voucherproduct.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.KvProductID(); ok {
		_spec.SetField(voucherproduct.FieldKvProductID, field.TypeInt64, value)
		_node.KvProductID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(voucherproduct.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Denomination(); ok {
		_spec.SetField(voucherproduct.FieldDenomination, field.TypeFloat64, value)
		_node.Denomination = value
	}
	if value, ok := _c.mutation.WholesalePrice(); ok {
		_spec.SetField(voucherproduct.FieldWholesalePrice, field.TypeFloat64, value)
		_node.WholesalePrice = value
	}
	if value, ok := _c.mutation.RetailPrice(); ok {
		_spec.SetField(voucherproduct.FieldRetailPrice, field.TypeFloat64, value)
		_node.RetailPrice = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(voucherproduct.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.StockAvailable(); ok {
		_spec.SetField(voucherproduct.FieldStockAvailable, field.TypeInt, value)
		_node.StockAvailable = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(voucherproduct.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(voucherproduct.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(voucherproduct.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(voucherproduct.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VoucherProduct.Create().
//		SetKvProductID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VoucherProductUpsert) {
//			SetKvProductID(v+v).
//		}).
//		Exec(ctx)
func (_c *VoucherProductCreate) OnConflict(opts ...sql.ConflictOption) *VoucherProductUpsertOne {
	_c.conflict = opts
	return &VoucherProductUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VoucherProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VoucherProductCreate) OnConflictColumns(columns ...string) *VoucherProductUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VoucherProductUpsertOne{
		create: _c,
	}
}

type (
	// VoucherProductUpsertOne is the builder for "upsert"-ing
	//  one VoucherProduct node.
	VoucherProductUpsertOne struct {
		create *VoucherProductCreate
	}

	// VoucherProductUpsert is the "OnConflict" setter.
	VoucherProductUpsert struct {
		*sql.UpdateSet
	}
)

// SetKvProductID sets the "kv_product_id" field.
func (u *VoucherProductUpsert) SetKvProductID(v int64) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldKvProductID, v)
	return u
}

// UpdateKvProductID sets the "kv_product_id" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateKvProductID() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldKvProductID)
	return u
}

// AddKvProductID adds v to the "kv_product_id" field.
func (u *VoucherProductUpsert) AddKvProductID(v int64) *VoucherProductUpsert {
	u.Add(voucherproduct.FieldKvProductID, v)
	return u
}

// ClearKvProductID clears the value of the "kv_product_id" field.
func (u *VoucherProductUpsert) ClearKvProductID() *VoucherProductUpsert {
	u.SetNull(voucherproduct.FieldKvProductID)
	return u
}

// SetName sets the "name" field.
func (u *VoucherProductUpsert) SetName(v string) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateName() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldName)
	return u
}

// SetDenomination sets the "denomination" field.
func (u *VoucherProductUpsert) SetDenomination(v float64) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldDenomination, v)
	return u
}

// UpdateDenomination sets the "denomination" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateDenomination() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldDenomination)
	return u
}

// AddDenomination adds v to the "denomination" field.
func (u *VoucherProductUpsert) AddDenomination(v float64) *VoucherProductUpsert {
	u.Add(voucherproduct.FieldDenomination, v)
	return u
}

// SetWholesalePrice sets the "wholesale_price" field.
func (u *VoucherProductUpsert) SetWholesalePrice(v float64) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldWholesalePrice, v)
	return u
}

// UpdateWholesalePrice sets the "wholesale_price" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateWholesalePrice() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldWholesalePrice)
	return u
}

// AddWholesalePrice adds v to the "wholesale_price" field.
func (u *VoucherProductUpsert) AddWholesalePrice(v float64) *VoucherProductUpsert {
	u.Add(voucherproduct.FieldWholesalePrice, v)
	return u
}

// SetRetailPrice sets the "retail_price" field.
func (u *VoucherProductUpsert) SetRetailPrice(v float64) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldRetailPrice, v)
	return u
}

// UpdateRetailPrice sets the "retail_price" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateRetailPrice() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldRetailPrice)
	return u
}

// AddRetailPrice adds v to the "retail_price" field.
func (u *VoucherProductUpsert) AddRetailPrice(v float64) *VoucherProductUpsert {
	u.Add(voucherproduct.FieldRetailPrice, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *VoucherProductUpsert) SetCurrency(v string) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateCurrency() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldCurrency)
	return u
}

// SetStockAvailable sets the "stock_available" field.
func (u *VoucherProductUpsert) SetStockAvailable(v int) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldStockAvailable, v)
	return u
}

// UpdateStockAvailable sets the "stock_available" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateStockAvailable() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldStockAvailable)
	return u
}

// AddStockAvailable adds v to the "stock_available" field.
func (u *VoucherProductUpsert) AddStockAvailable(v int) *VoucherProductUpsert {
	u.Add(voucherproduct.FieldStockAvailable, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *VoucherProductUpsert) SetIsActive(v bool) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateIsActive() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldIsActive)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *VoucherProductUpsert) SetSortOrder(v int) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateSortOrder() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *VoucherProductUpsert) AddSortOrder(v int) *VoucherProductUpsert {
	u.Add(voucherproduct.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VoucherProductUpsert) SetUpdatedAt(v time.Time) *VoucherProductUpsert {
	u.Set(voucherproduct.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VoucherProductUpsert) UpdateUpdatedAt() *VoucherProductUpsert {
	u.SetExcluded(voucherproduct.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VoucherProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VoucherProductUpsertOne) UpdateNewValues() *VoucherProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(voucherproduct.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VoucherProduct.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VoucherProductUpsertOne) Ignore() *VoucherProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VoucherProductUpsertOne) DoNothing() *VoucherProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VoucherProductCreate.OnConflict
// documentation for more info.
func (u *VoucherProductUpsertOne) Update(set func(*VoucherProductUpsert)) *VoucherProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VoucherProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetKvProductID sets the "kv_product_id" field.
func (u *VoucherProductUpsertOne) SetKvProductID(v int64) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetKvProductID(v)
	})
}

// AddKvProductID adds v to the "kv_product_id" field.
func (u *VoucherProductUpsertOne) AddKvProductID(v int64) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddKvProductID(v)
	})
}

// UpdateKvProductID sets the "kv_product_id" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateKvProductID() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateKvProductID()
	})
}

// ClearKvProductID clears the value of the "kv_product_id" field.
func (u *VoucherProductUpsertOne) ClearKvProductID() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.ClearKvProductID()
	})
}

// SetName sets the "name" field.
func (u *VoucherProductUpsertOne) SetName(v string) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateName() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateName()
	})
}

// SetDenomination sets the "denomination" field.
func (u *VoucherProductUpsertOne) SetDenomination(v float64) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetDenomination(v)
	})
}

// AddDenomination adds v to the "denomination" field.
func (u *VoucherProductUpsertOne) AddDenomination(v float64) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddDenomination(v)
	})
}

// UpdateDenomination sets the "denomination" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateDenomination() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateDenomination()
	})
}

// SetWholesalePrice sets the "wholesale_price" field.
func (u *VoucherProductUpsertOne) SetWholesalePrice(v float64) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetWholesalePrice(v)
	})
}

// AddWholesalePrice adds v to the "wholesale_price" field.
func (u *VoucherProductUpsertOne) AddWholesalePrice(v float64) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddWholesalePrice(v)
	})
}

// UpdateWholesalePrice sets the "wholesale_price" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateWholesalePrice() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateWholesalePrice()
	})
}

// SetRetailPrice sets the "retail_price" field.
func (u *VoucherProductUpsertOne) SetRetailPrice(v float64) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetRetailPrice(v)
	})
}

// AddRetailPrice adds v to the "retail_price" field.
func (u *VoucherProductUpsertOne) AddRetailPrice(v float64) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddRetailPrice(v)
	})
}

// UpdateRetailPrice sets the "retail_price" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateRetailPrice() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateRetailPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *VoucherProductUpsertOne) SetCurrency(v string) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateCurrency() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateCurrency()
	})
}

// SetStockAvailable sets the "stock_available" field.
func (u *VoucherProductUpsertOne) SetStockAvailable(v int) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetStockAvailable(v)
	})
}

// AddStockAvailable adds v to the "stock_available" field.
func (u *VoucherProductUpsertOne) AddStockAvailable(v int) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddStockAvailable(v)
	})
}

// UpdateStockAvailable sets the "stock_available" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateStockAvailable() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateStockAvailable()
	})
}

// SetIsActive sets the "is_active" field.
func (u *VoucherProductUpsertOne) SetIsActive(v bool) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateIsActive() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateIsActive()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *VoucherProductUpsertOne) SetSortOrder(v int) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *VoucherProductUpsertOne) AddSortOrder(v int) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateSortOrder() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VoucherProductUpsertOne) SetUpdatedAt(v time.Time) *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VoucherProductUpsertOne) UpdateUpdatedAt() *VoucherProductUpsertOne {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VoucherProductUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VoucherProductCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VoucherProductUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VoucherProductUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VoucherProductUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VoucherProductCreateBulk is the builder for creating many VoucherProduct entities in bulk.
type VoucherProductCreateBulk struct {
	config
	err      error
	builders []*VoucherProductCreate
	conflict []sql.ConflictOption
}

// Save creates the VoucherProduct entities in the database.
func (_c *VoucherProductCreateBulk) Save(ctx context.Context) ([]*VoucherProduct, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VoucherProduct, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VoucherProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VoucherProductCreateBulk) SaveX(ctx context.Context) []*VoucherProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VoucherProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VoucherProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VoucherProduct.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VoucherProductUpsert) {
//			SetKvProductID(v+v).
//		}).
//		Exec(ctx)
func (_c *VoucherProductCreateBulk) OnConflict(opts ...sql.ConflictOption) *VoucherProductUpsertBulk {
	_c.conflict = opts
	return &VoucherProductUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VoucherProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VoucherProductCreateBulk) OnConflictColumns(columns ...string) *VoucherProductUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VoucherProductUpsertBulk{
		create: _c,
	}
}

// VoucherProductUpsertBulk is the builder for "upsert"-ing
// a bulk of VoucherProduct nodes.
type VoucherProductUpsertBulk struct {
	create *VoucherProductCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VoucherProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VoucherProductUpsertBulk) UpdateNewValues() *VoucherProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(voucherproduct.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VoucherProduct.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VoucherProductUpsertBulk) Ignore() *VoucherProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VoucherProductUpsertBulk) DoNothing() *VoucherProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VoucherProductCreateBulk.OnConflict
// documentation for more info.
func (u *VoucherProductUpsertBulk) Update(set func(*VoucherProductUpsert)) *VoucherProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VoucherProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetKvProductID sets the "kv_product_id" field.
func (u *VoucherProductUpsertBulk) SetKvProductID(v int64) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetKvProductID(v)
	})
}

// AddKvProductID adds v to the "kv_product_id" field.
func (u *VoucherProductUpsertBulk) AddKvProductID(v int64) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddKvProductID(v)
	})
}

// UpdateKvProductID sets the "kv_product_id" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateKvProductID() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateKvProductID()
	})
}

// ClearKvProductID clears the value of the "kv_product_id" field.
func (u *VoucherProductUpsertBulk) ClearKvProductID() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.ClearKvProductID()
	})
}

// SetName sets the "name" field.
func (u *VoucherProductUpsertBulk) SetName(v string) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateName() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateName()
	})
}

// SetDenomination sets the "denomination" field.
func (u *VoucherProductUpsertBulk) SetDenomination(v float64) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetDenomination(v)
	})
}

// AddDenomination adds v to the "denomination" field.
func (u *VoucherProductUpsertBulk) AddDenomination(v float64) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddDenomination(v)
	})
}

// UpdateDenomination sets the "denomination" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateDenomination() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateDenomination()
	})
}

// SetWholesalePrice sets the "wholesale_price" field.
func (u *VoucherProductUpsertBulk) SetWholesalePrice(v float64) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetWholesalePrice(v)
	})
}

// AddWholesalePrice adds v to the "wholesale_price" field.
func (u *VoucherProductUpsertBulk) AddWholesalePrice(v float64) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddWholesalePrice(v)
	})
}

// UpdateWholesalePrice sets the "wholesale_price" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateWholesalePrice() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateWholesalePrice()
	})
}

// SetRetailPrice sets the "retail_price" field.
func (u *VoucherProductUpsertBulk) SetRetailPrice(v float64) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetRetailPrice(v)
	})
}

// AddRetailPrice adds v to the "retail_price" field.
func (u *VoucherProductUpsertBulk) AddRetailPrice(v float64) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddRetailPrice(v)
	})
}

// UpdateRetailPrice sets the "retail_price" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateRetailPrice() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateRetailPrice()
	})
}

// SetCurrency sets the "currency" field.
func (u *VoucherProductUpsertBulk) SetCurrency(v string) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateCurrency() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateCurrency()
	})
}

// SetStockAvailable sets the "stock_available" field.
func (u *VoucherProductUpsertBulk) SetStockAvailable(v int) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetStockAvailable(v)
	})
}

// AddStockAvailable adds v to the "stock_available" field.
func (u *VoucherProductUpsertBulk) AddStockAvailable(v int) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddStockAvailable(v)
	})
}

// UpdateStockAvailable sets the "stock_available" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateStockAvailable() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateStockAvailable()
	})
}

// SetIsActive sets the "is_active" field.
func (u *VoucherProductUpsertBulk) SetIsActive(v bool) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateIsActive() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateIsActive()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *VoucherProductUpsertBulk) SetSortOrder(v int) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *VoucherProductUpsertBulk) AddSortOrder(v int) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateSortOrder() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VoucherProductUpsertBulk) SetUpdatedAt(v time.Time) *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VoucherProductUpsertBulk) UpdateUpdatedAt() *VoucherProductUpsertBulk {
	return u.Update(func(s *VoucherProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VoucherProductUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VoucherProductCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VoucherProductCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VoucherProductUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
