// Code generated by ent, DO NOT EDIT.

package voucherproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the voucherproduct type in the database.
	Label = "voucher_product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKvProductID holds the string denoting the kv_product_id field in the database.
	FieldKvProductID = "kv_product_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDenomination holds the string denoting the denomination field in the database.
	FieldDenomination = "denomination"
	// FieldWholesalePrice holds the string denoting the wholesale_price field in the database.
	FieldWholesalePrice = "wholesale_price"
	// FieldRetailPrice holds the string denoting the retail_price field in the database.
	FieldRetailPrice = "retail_price"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldStockAvailable holds the string denoting the stock_available field in the database.
	FieldStockAvailable = "stock_available"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the voucherproduct in the database.
	Table = "voucher_products"
)

// Columns holds all SQL columns for voucherproduct fields.
var Columns = []string{
	FieldID,
	FieldKvProductID,
	FieldName,
	FieldDenomination,
	FieldWholesalePrice,
	FieldRetailPrice,
	FieldCurrency,
	FieldStockAvailable,
	FieldIsActive,
	FieldSortOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultWholesalePrice holds the default value on creation for the "wholesale_price" field.
	DefaultWholesalePrice float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultStockAvailable holds the default value on creation for the "stock_available" field.
	DefaultStockAvailable int
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the VoucherProduct queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKvProductID orders the results by the kv_product_id field.
func ByKvProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKvProductID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDenomination orders the results by the denomination field.
func ByDenomination(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDenomination, opts...).ToFunc()
}

// ByWholesalePrice orders the results by the wholesale_price field.
func ByWholesalePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWholesalePrice, opts...).ToFunc()
}

// ByRetailPrice orders the results by the retail_price field.
func ByRetailPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetailPrice, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByStockAvailable orders the results by the stock_available field.
func ByStockAvailable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStockAvailable, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
