// Code generated by ent, DO NOT EDIT.

package voucherproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldID, id))
}

// KvProductID applies equality check predicate on the "kv_product_id" field. It's identical to KvProductIDEQ.
func KvProductID(v int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldKvProductID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldName, v))
}

// Denomination applies equality check predicate on the "denomination" field. It's identical to DenominationEQ.
func Denomination(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldDenomination, v))
}

// WholesalePrice applies equality check predicate on the "wholesale_price" field. It's identical to WholesalePriceEQ.
func WholesalePrice(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldWholesalePrice, v))
}

// RetailPrice applies equality check predicate on the "retail_price" field. It's identical to RetailPriceEQ.
func RetailPrice(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldRetailPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldCurrency, v))
}

// StockAvailable applies equality check predicate on the "stock_available" field. It's identical to StockAvailableEQ.
func StockAvailable(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldStockAvailable, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldIsActive, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// KvProductIDEQ applies the EQ predicate on the "kv_product_id" field.
func KvProductIDEQ(v int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldKvProductID, v))
}

// KvProductIDNEQ applies the NEQ predicate on the "kv_product_id" field.
func KvProductIDNEQ(v int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldKvProductID, v))
}

// KvProductIDIn applies the In predicate on the "kv_product_id" field.
func KvProductIDIn(vs ...int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldKvProductID, vs...))
}

// KvProductIDNotIn applies the NotIn predicate on the "kv_product_id" field.
func KvProductIDNotIn(vs ...int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldKvProductID, vs...))
}

// KvProductIDGT applies the GT predicate on the "kv_product_id" field.
func KvProductIDGT(v int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldKvProductID, v))
}

// KvProductIDGTE applies the GTE predicate on the "kv_product_id" field.
func KvProductIDGTE(v int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldKvProductID, v))
}

// KvProductIDLT applies the LT predicate on the "kv_product_id" field.
func KvProductIDLT(v int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldKvProductID, v))
}

// KvProductIDLTE applies the LTE predicate on the "kv_product_id" field.
func KvProductIDLTE(v int64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldKvProductID, v))
}

// KvProductIDIsNil applies the IsNil predicate on the "kv_product_id" field.
func KvProductIDIsNil() predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIsNull(FieldKvProductID))
}

// KvProductIDNotNil applies the NotNil predicate on the "kv_product_id" field.
func KvProductIDNotNil() predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotNull(FieldKvProductID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldContainsFold(FieldName, v))
}

// DenominationEQ applies the EQ predicate on the "denomination" field.
func DenominationEQ(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldDenomination, v))
}

// DenominationNEQ applies the NEQ predicate on the "denomination" field.
func DenominationNEQ(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldDenomination, v))
}

// DenominationIn applies the In predicate on the "denomination" field.
func DenominationIn(vs ...float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldDenomination, vs...))
}

// DenominationNotIn applies the NotIn predicate on the "denomination" field.
func DenominationNotIn(vs ...float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldDenomination, vs...))
}

// DenominationGT applies the GT predicate on the "denomination" field.
func DenominationGT(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldDenomination, v))
}

// DenominationGTE applies the GTE predicate on the "denomination" field.
func DenominationGTE(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldDenomination, v))
}

// DenominationLT applies the LT predicate on the "denomination" field.
func DenominationLT(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldDenomination, v))
}

// DenominationLTE applies the LTE predicate on the "denomination" field.
func DenominationLTE(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldDenomination, v))
}

// WholesalePriceEQ applies the EQ predicate on the "wholesale_price" field.
func WholesalePriceEQ(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldWholesalePrice, v))
}

// WholesalePriceNEQ applies the NEQ predicate on the "wholesale_price" field.
func WholesalePriceNEQ(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldWholesalePrice, v))
}

// WholesalePriceIn applies the In predicate on the "wholesale_price" field.
func WholesalePriceIn(vs ...float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldWholesalePrice, vs...))
}

// WholesalePriceNotIn applies the NotIn predicate on the "wholesale_price" field.
func WholesalePriceNotIn(vs ...float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldWholesalePrice, vs...))
}

// WholesalePriceGT applies the GT predicate on the "wholesale_price" field.
func WholesalePriceGT(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldWholesalePrice, v))
}

// WholesalePriceGTE applies the GTE predicate on the "wholesale_price" field.
func WholesalePriceGTE(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldWholesalePrice, v))
}

// WholesalePriceLT applies the LT predicate on the "wholesale_price" field.
func WholesalePriceLT(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldWholesalePrice, v))
}

// WholesalePriceLTE applies the LTE predicate on the "wholesale_price" field.
func WholesalePriceLTE(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldWholesalePrice, v))
}

// RetailPriceEQ applies the EQ predicate on the "retail_price" field.
func RetailPriceEQ(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldRetailPrice, v))
}

// RetailPriceNEQ applies the NEQ predicate on the "retail_price" field.
func RetailPriceNEQ(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldRetailPrice, v))
}

// RetailPriceIn applies the In predicate on the "retail_price" field.
func RetailPriceIn(vs ...float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldRetailPrice, vs...))
}

// RetailPriceNotIn applies the NotIn predicate on the "retail_price" field.
func RetailPriceNotIn(vs ...float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldRetailPrice, vs...))
}

// RetailPriceGT applies the GT predicate on the "retail_price" field.
func RetailPriceGT(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldRetailPrice, v))
}

// RetailPriceGTE applies the GTE predicate on the "retail_price" field.
func RetailPriceGTE(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldRetailPrice, v))
}

// RetailPriceLT applies the LT predicate on the "retail_price" field.
func RetailPriceLT(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldRetailPrice, v))
}

// RetailPriceLTE applies the LTE predicate on the "retail_price" field.
func RetailPriceLTE(v float64) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldRetailPrice, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldContainsFold(FieldCurrency, v))
}

// StockAvailableEQ applies the EQ predicate on the "stock_available" field.
func StockAvailableEQ(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldStockAvailable, v))
}

// StockAvailableNEQ applies the NEQ predicate on the "stock_available" field.
func StockAvailableNEQ(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldStockAvailable, v))
}

// StockAvailableIn applies the In predicate on the "stock_available" field.
func StockAvailableIn(vs ...int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldStockAvailable, vs...))
}

// StockAvailableNotIn applies the NotIn predicate on the "stock_available" field.
func StockAvailableNotIn(vs ...int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldStockAvailable, vs...))
}

// StockAvailableGT applies the GT predicate on the "stock_available" field.
func StockAvailableGT(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldStockAvailable, v))
}

// StockAvailableGTE applies the GTE predicate on the "stock_available" field.
func StockAvailableGTE(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldStockAvailable, v))
}

// StockAvailableLT applies the LT predicate on the "stock_available" field.
func StockAvailableLT(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldStockAvailable, v))
}

// StockAvailableLTE applies the LTE predicate on the "stock_available" field.
func StockAvailableLTE(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldStockAvailable, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldIsActive, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VoucherProduct) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VoucherProduct) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VoucherProduct) predicate.VoucherProduct {
	return predicate.VoucherProduct(sql.NotPredicates(p))
}
