// Code generated by ent, DO NOT EDIT.

package voucherb2border

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the voucherb2border type in the database.
	Label = "voucher_b2b_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKvOrderID holds the string denoting the kv_order_id field in the database.
	FieldKvOrderID = "kv_order_id"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSubtotal holds the string denoting the subtotal field in the database.
	FieldSubtotal = "subtotal"
	// FieldFeeAmount holds the string denoting the fee_amount field in the database.
	FieldFeeAmount = "fee_amount"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldItemsJSON holds the string denoting the items_json field in the database.
	FieldItemsJSON = "items_json"
	// FieldPaymentInfoJSON holds the string denoting the payment_info_json field in the database.
	FieldPaymentInfoJSON = "payment_info_json"
	// FieldPaymentRef holds the string denoting the payment_ref field in the database.
	FieldPaymentRef = "payment_ref"
	// FieldPaymentProofPath holds the string denoting the payment_proof_path field in the database.
	FieldPaymentProofPath = "payment_proof_path"
	// FieldBankAccountID holds the string denoting the bank_account_id field in the database.
	FieldBankAccountID = "bank_account_id"
	// FieldMerchantNotes holds the string denoting the merchant_notes field in the database.
	FieldMerchantNotes = "merchant_notes"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldRejectReason holds the string denoting the reject_reason field in the database.
	FieldRejectReason = "reject_reason"
	// FieldKvLastRequestID holds the string denoting the kv_last_request_id field in the database.
	FieldKvLastRequestID = "kv_last_request_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldKvLastSyncedAt holds the string denoting the kv_last_synced_at field in the database.
	FieldKvLastSyncedAt = "kv_last_synced_at"
	// FieldVerifiedAt holds the string denoting the verified_at field in the database.
	FieldVerifiedAt = "verified_at"
	// FieldPinsLoadedAt holds the string denoting the pins_loaded_at field in the database.
	FieldPinsLoadedAt = "pins_loaded_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the voucherb2border in the database.
	Table = "voucher_b2b_orders"
)

// Columns holds all SQL columns for voucherb2border fields.
var Columns = []string{
	FieldID,
	FieldKvOrderID,
	FieldOrderNo,
	FieldStatus,
	FieldSubtotal,
	FieldFeeAmount,
	FieldTotalAmount,
	FieldCurrency,
	FieldItemsJSON,
	FieldPaymentInfoJSON,
	FieldPaymentRef,
	FieldPaymentProofPath,
	FieldBankAccountID,
	FieldMerchantNotes,
	FieldIdempotencyKey,
	FieldRejectReason,
	FieldKvLastRequestID,
	FieldCreatedBy,
	FieldKvLastSyncedAt,
	FieldVerifiedAt,
	FieldPinsLoadedAt,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	OrderNoValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultFeeAmount holds the default value on creation for the "fee_amount" field.
	DefaultFeeAmount float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// PaymentRefValidator is a validator for the "payment_ref" field. It is called by the builders before save.
	PaymentRefValidator func(string) error
	// PaymentProofPathValidator is a validator for the "payment_proof_path" field. It is called by the builders before save.
	PaymentProofPathValidator func(string) error
	// MerchantNotesValidator is a validator for the "merchant_notes" field. It is called by the builders before save.
	MerchantNotesValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// KvLastRequestIDValidator is a validator for the "kv_last_request_id" field. It is called by the builders before save.
	KvLastRequestIDValidator func(string) error
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy string
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the VoucherB2BOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKvOrderID orders the results by the kv_order_id field.
func ByKvOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKvOrderID, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySubtotal orders the results by the subtotal field.
func BySubtotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubtotal, opts...).ToFunc()
}

// ByFeeAmount orders the results by the fee_amount field.
func ByFeeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeAmount, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByPaymentRef orders the results by the payment_ref field.
func ByPaymentRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentRef, opts...).ToFunc()
}

// ByPaymentProofPath orders the results by the payment_proof_path field.
func ByPaymentProofPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentProofPath, opts...).ToFunc()
}

// ByBankAccountID orders the results by the bank_account_id field.
func ByBankAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBankAccountID, opts...).ToFunc()
}

// ByMerchantNotes orders the results by the merchant_notes field.
func ByMerchantNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerchantNotes, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByRejectReason orders the results by the reject_reason field.
func ByRejectReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRejectReason, opts...).ToFunc()
}

// ByKvLastRequestID orders the results by the kv_last_request_id field.
func ByKvLastRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKvLastRequestID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByKvLastSyncedAt orders the results by the kv_last_synced_at field.
func ByKvLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKvLastSyncedAt, opts...).ToFunc()
}

// ByVerifiedAt orders the results by the verified_at field.
func ByVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifiedAt, opts...).ToFunc()
}

// ByPinsLoadedAt orders the results by the pins_loaded_at field.
func ByPinsLoadedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPinsLoadedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
