// Code generated by ent, DO NOT EDIT.

package voucherb2border

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldID, id))
}

// KvOrderID applies equality check predicate on the "kv_order_id" field. It's identical to KvOrderIDEQ.
func KvOrderID(v int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldKvOrderID, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldOrderNo, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldStatus, v))
}

// Subtotal applies equality check predicate on the "subtotal" field. It's identical to SubtotalEQ.
func Subtotal(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldSubtotal, v))
}

// FeeAmount applies equality check predicate on the "fee_amount" field. It's identical to FeeAmountEQ.
func FeeAmount(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldFeeAmount, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldTotalAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldCurrency, v))
}

// PaymentRef applies equality check predicate on the "payment_ref" field. It's identical to PaymentRefEQ.
func PaymentRef(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldPaymentRef, v))
}

// PaymentProofPath applies equality check predicate on the "payment_proof_path" field. It's identical to PaymentProofPathEQ.
func PaymentProofPath(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldPaymentProofPath, v))
}

// BankAccountID applies equality check predicate on the "bank_account_id" field. It's identical to BankAccountIDEQ.
func BankAccountID(v int) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldBankAccountID, v))
}

// MerchantNotes applies equality check predicate on the "merchant_notes" field. It's identical to MerchantNotesEQ.
func MerchantNotes(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldMerchantNotes, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldIdempotencyKey, v))
}

// RejectReason applies equality check predicate on the "reject_reason" field. It's identical to RejectReasonEQ.
func RejectReason(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldRejectReason, v))
}

// KvLastRequestID applies equality check predicate on the "kv_last_request_id" field. It's identical to KvLastRequestIDEQ.
func KvLastRequestID(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldKvLastRequestID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldCreatedBy, v))
}

// KvLastSyncedAt applies equality check predicate on the "kv_last_synced_at" field. It's identical to KvLastSyncedAtEQ.
func KvLastSyncedAt(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldKvLastSyncedAt, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldVerifiedAt, v))
}

// PinsLoadedAt applies equality check predicate on the "pins_loaded_at" field. It's identical to PinsLoadedAtEQ.
func PinsLoadedAt(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldPinsLoadedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// KvOrderIDEQ applies the EQ predicate on the "kv_order_id" field.
func KvOrderIDEQ(v int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldKvOrderID, v))
}

// KvOrderIDNEQ applies the NEQ predicate on the "kv_order_id" field.
func KvOrderIDNEQ(v int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldKvOrderID, v))
}

// KvOrderIDIn applies the In predicate on the "kv_order_id" field.
func KvOrderIDIn(vs ...int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldKvOrderID, vs...))
}

// KvOrderIDNotIn applies the NotIn predicate on the "kv_order_id" field.
func KvOrderIDNotIn(vs ...int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldKvOrderID, vs...))
}

// KvOrderIDGT applies the GT predicate on the "kv_order_id" field.
func KvOrderIDGT(v int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldKvOrderID, v))
}

// KvOrderIDGTE applies the GTE predicate on the "kv_order_id" field.
func KvOrderIDGTE(v int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldKvOrderID, v))
}

// KvOrderIDLT applies the LT predicate on the "kv_order_id" field.
func KvOrderIDLT(v int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldKvOrderID, v))
}

// KvOrderIDLTE applies the LTE predicate on the "kv_order_id" field.
func KvOrderIDLTE(v int64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldKvOrderID, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldStatus, v))
}

// SubtotalEQ applies the EQ predicate on the "subtotal" field.
func SubtotalEQ(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldSubtotal, v))
}

// SubtotalNEQ applies the NEQ predicate on the "subtotal" field.
func SubtotalNEQ(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldSubtotal, v))
}

// SubtotalIn applies the In predicate on the "subtotal" field.
func SubtotalIn(vs ...float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldSubtotal, vs...))
}

// SubtotalNotIn applies the NotIn predicate on the "subtotal" field.
func SubtotalNotIn(vs ...float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldSubtotal, vs...))
}

// SubtotalGT applies the GT predicate on the "subtotal" field.
func SubtotalGT(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldSubtotal, v))
}

// SubtotalGTE applies the GTE predicate on the "subtotal" field.
func SubtotalGTE(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldSubtotal, v))
}

// SubtotalLT applies the LT predicate on the "subtotal" field.
func SubtotalLT(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldSubtotal, v))
}

// SubtotalLTE applies the LTE predicate on the "subtotal" field.
func SubtotalLTE(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldSubtotal, v))
}

// FeeAmountEQ applies the EQ predicate on the "fee_amount" field.
func FeeAmountEQ(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldFeeAmount, v))
}

// FeeAmountNEQ applies the NEQ predicate on the "fee_amount" field.
func FeeAmountNEQ(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldFeeAmount, v))
}

// FeeAmountIn applies the In predicate on the "fee_amount" field.
func FeeAmountIn(vs ...float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldFeeAmount, vs...))
}

// FeeAmountNotIn applies the NotIn predicate on the "fee_amount" field.
func FeeAmountNotIn(vs ...float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldFeeAmount, vs...))
}

// FeeAmountGT applies the GT predicate on the "fee_amount" field.
func FeeAmountGT(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldFeeAmount, v))
}

// FeeAmountGTE applies the GTE predicate on the "fee_amount" field.
func FeeAmountGTE(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldFeeAmount, v))
}

// FeeAmountLT applies the LT predicate on the "fee_amount" field.
func FeeAmountLT(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldFeeAmount, v))
}

// FeeAmountLTE applies the LTE predicate on the "fee_amount" field.
func FeeAmountLTE(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldFeeAmount, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v float64) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldTotalAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldCurrency, v))
}

// PaymentInfoJSONIsNil applies the IsNil predicate on the "payment_info_json" field.
func PaymentInfoJSONIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldPaymentInfoJSON))
}

// PaymentInfoJSONNotNil applies the NotNil predicate on the "payment_info_json" field.
func PaymentInfoJSONNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldPaymentInfoJSON))
}

// PaymentRefEQ applies the EQ predicate on the "payment_ref" field.
func PaymentRefEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldPaymentRef, v))
}

// PaymentRefNEQ applies the NEQ predicate on the "payment_ref" field.
func PaymentRefNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldPaymentRef, v))
}

// PaymentRefIn applies the In predicate on the "payment_ref" field.
func PaymentRefIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldPaymentRef, vs...))
}

// PaymentRefNotIn applies the NotIn predicate on the "payment_ref" field.
func PaymentRefNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldPaymentRef, vs...))
}

// PaymentRefGT applies the GT predicate on the "payment_ref" field.
func PaymentRefGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldPaymentRef, v))
}

// PaymentRefGTE applies the GTE predicate on the "payment_ref" field.
func PaymentRefGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldPaymentRef, v))
}

// PaymentRefLT applies the LT predicate on the "payment_ref" field.
func PaymentRefLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldPaymentRef, v))
}

// PaymentRefLTE applies the LTE predicate on the "payment_ref" field.
func PaymentRefLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldPaymentRef, v))
}

// PaymentRefContains applies the Contains predicate on the "payment_ref" field.
func PaymentRefContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldPaymentRef, v))
}

// PaymentRefHasPrefix applies the HasPrefix predicate on the "payment_ref" field.
func PaymentRefHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldPaymentRef, v))
}

// PaymentRefHasSuffix applies the HasSuffix predicate on the "payment_ref" field.
func PaymentRefHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldPaymentRef, v))
}

// PaymentRefIsNil applies the IsNil predicate on the "payment_ref" field.
func PaymentRefIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldPaymentRef))
}

// PaymentRefNotNil applies the NotNil predicate on the "payment_ref" field.
func PaymentRefNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldPaymentRef))
}

// PaymentRefEqualFold applies the EqualFold predicate on the "payment_ref" field.
func PaymentRefEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldPaymentRef, v))
}

// PaymentRefContainsFold applies the ContainsFold predicate on the "payment_ref" field.
func PaymentRefContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldPaymentRef, v))
}

// PaymentProofPathEQ applies the EQ predicate on the "payment_proof_path" field.
func PaymentProofPathEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldPaymentProofPath, v))
}

// PaymentProofPathNEQ applies the NEQ predicate on the "payment_proof_path" field.
func PaymentProofPathNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldPaymentProofPath, v))
}

// PaymentProofPathIn applies the In predicate on the "payment_proof_path" field.
func PaymentProofPathIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldPaymentProofPath, vs...))
}

// PaymentProofPathNotIn applies the NotIn predicate on the "payment_proof_path" field.
func PaymentProofPathNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldPaymentProofPath, vs...))
}

// PaymentProofPathGT applies the GT predicate on the "payment_proof_path" field.
func PaymentProofPathGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldPaymentProofPath, v))
}

// PaymentProofPathGTE applies the GTE predicate on the "payment_proof_path" field.
func PaymentProofPathGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldPaymentProofPath, v))
}

// PaymentProofPathLT applies the LT predicate on the "payment_proof_path" field.
func PaymentProofPathLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldPaymentProofPath, v))
}

// PaymentProofPathLTE applies the LTE predicate on the "payment_proof_path" field.
func PaymentProofPathLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldPaymentProofPath, v))
}

// PaymentProofPathContains applies the Contains predicate on the "payment_proof_path" field.
func PaymentProofPathContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldPaymentProofPath, v))
}

// PaymentProofPathHasPrefix applies the HasPrefix predicate on the "payment_proof_path" field.
func PaymentProofPathHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldPaymentProofPath, v))
}

// PaymentProofPathHasSuffix applies the HasSuffix predicate on the "payment_proof_path" field.
func PaymentProofPathHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldPaymentProofPath, v))
}

// PaymentProofPathIsNil applies the IsNil predicate on the "payment_proof_path" field.
func PaymentProofPathIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldPaymentProofPath))
}

// PaymentProofPathNotNil applies the NotNil predicate on the "payment_proof_path" field.
func PaymentProofPathNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldPaymentProofPath))
}

// PaymentProofPathEqualFold applies the EqualFold predicate on the "payment_proof_path" field.
func PaymentProofPathEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldPaymentProofPath, v))
}

// PaymentProofPathContainsFold applies the ContainsFold predicate on the "payment_proof_path" field.
func PaymentProofPathContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldPaymentProofPath, v))
}

// BankAccountIDEQ applies the EQ predicate on the "bank_account_id" field.
func BankAccountIDEQ(v int) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldBankAccountID, v))
}

// BankAccountIDNEQ applies the NEQ predicate on the "bank_account_id" field.
func BankAccountIDNEQ(v int) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldBankAccountID, v))
}

// BankAccountIDIn applies the In predicate on the "bank_account_id" field.
func BankAccountIDIn(vs ...int) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldBankAccountID, vs...))
}

// BankAccountIDNotIn applies the NotIn predicate on the "bank_account_id" field.
func BankAccountIDNotIn(vs ...int) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldBankAccountID, vs...))
}

// BankAccountIDGT applies the GT predicate on the "bank_account_id" field.
func BankAccountIDGT(v int) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldBankAccountID, v))
}

// BankAccountIDGTE applies the GTE predicate on the "bank_account_id" field.
func BankAccountIDGTE(v int) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldBankAccountID, v))
}

// BankAccountIDLT applies the LT predicate on the "bank_account_id" field.
func BankAccountIDLT(v int) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldBankAccountID, v))
}

// BankAccountIDLTE applies the LTE predicate on the "bank_account_id" field.
func BankAccountIDLTE(v int) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldBankAccountID, v))
}

// BankAccountIDIsNil applies the IsNil predicate on the "bank_account_id" field.
func BankAccountIDIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldBankAccountID))
}

// BankAccountIDNotNil applies the NotNil predicate on the "bank_account_id" field.
func BankAccountIDNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldBankAccountID))
}

// MerchantNotesEQ applies the EQ predicate on the "merchant_notes" field.
func MerchantNotesEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldMerchantNotes, v))
}

// MerchantNotesNEQ applies the NEQ predicate on the "merchant_notes" field.
func MerchantNotesNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldMerchantNotes, v))
}

// MerchantNotesIn applies the In predicate on the "merchant_notes" field.
func MerchantNotesIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldMerchantNotes, vs...))
}

// MerchantNotesNotIn applies the NotIn predicate on the "merchant_notes" field.
func MerchantNotesNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldMerchantNotes, vs...))
}

// MerchantNotesGT applies the GT predicate on the "merchant_notes" field.
func MerchantNotesGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldMerchantNotes, v))
}

// MerchantNotesGTE applies the GTE predicate on the "merchant_notes" field.
func MerchantNotesGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldMerchantNotes, v))
}

// MerchantNotesLT applies the LT predicate on the "merchant_notes" field.
func MerchantNotesLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldMerchantNotes, v))
}

// MerchantNotesLTE applies the LTE predicate on the "merchant_notes" field.
func MerchantNotesLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldMerchantNotes, v))
}

// MerchantNotesContains applies the Contains predicate on the "merchant_notes" field.
func MerchantNotesContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldMerchantNotes, v))
}

// MerchantNotesHasPrefix applies the HasPrefix predicate on the "merchant_notes" field.
func MerchantNotesHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldMerchantNotes, v))
}

// MerchantNotesHasSuffix applies the HasSuffix predicate on the "merchant_notes" field.
func MerchantNotesHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldMerchantNotes, v))
}

// MerchantNotesIsNil applies the IsNil predicate on the "merchant_notes" field.
func MerchantNotesIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldMerchantNotes))
}

// MerchantNotesNotNil applies the NotNil predicate on the "merchant_notes" field.
func MerchantNotesNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldMerchantNotes))
}

// MerchantNotesEqualFold applies the EqualFold predicate on the "merchant_notes" field.
func MerchantNotesEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldMerchantNotes, v))
}

// MerchantNotesContainsFold applies the ContainsFold predicate on the "merchant_notes" field.
func MerchantNotesContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldMerchantNotes, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// RejectReasonEQ applies the EQ predicate on the "reject_reason" field.
func RejectReasonEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldRejectReason, v))
}

// RejectReasonNEQ applies the NEQ predicate on the "reject_reason" field.
func RejectReasonNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldRejectReason, v))
}

// RejectReasonIn applies the In predicate on the "reject_reason" field.
func RejectReasonIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldRejectReason, vs...))
}

// RejectReasonNotIn applies the NotIn predicate on the "reject_reason" field.
func RejectReasonNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldRejectReason, vs...))
}

// RejectReasonGT applies the GT predicate on the "reject_reason" field.
func RejectReasonGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldRejectReason, v))
}

// RejectReasonGTE applies the GTE predicate on the "reject_reason" field.
func RejectReasonGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldRejectReason, v))
}

// RejectReasonLT applies the LT predicate on the "reject_reason" field.
func RejectReasonLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldRejectReason, v))
}

// RejectReasonLTE applies the LTE predicate on the "reject_reason" field.
func RejectReasonLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldRejectReason, v))
}

// RejectReasonContains applies the Contains predicate on the "reject_reason" field.
func RejectReasonContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldRejectReason, v))
}

// RejectReasonHasPrefix applies the HasPrefix predicate on the "reject_reason" field.
func RejectReasonHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldRejectReason, v))
}

// RejectReasonHasSuffix applies the HasSuffix predicate on the "reject_reason" field.
func RejectReasonHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldRejectReason, v))
}

// RejectReasonIsNil applies the IsNil predicate on the "reject_reason" field.
func RejectReasonIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldRejectReason))
}

// RejectReasonNotNil applies the NotNil predicate on the "reject_reason" field.
func RejectReasonNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldRejectReason))
}

// RejectReasonEqualFold applies the EqualFold predicate on the "reject_reason" field.
func RejectReasonEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldRejectReason, v))
}

// RejectReasonContainsFold applies the ContainsFold predicate on the "reject_reason" field.
func RejectReasonContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldRejectReason, v))
}

// KvLastRequestIDEQ applies the EQ predicate on the "kv_last_request_id" field.
func KvLastRequestIDEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldKvLastRequestID, v))
}

// KvLastRequestIDNEQ applies the NEQ predicate on the "kv_last_request_id" field.
func KvLastRequestIDNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldKvLastRequestID, v))
}

// KvLastRequestIDIn applies the In predicate on the "kv_last_request_id" field.
func KvLastRequestIDIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldKvLastRequestID, vs...))
}

// KvLastRequestIDNotIn applies the NotIn predicate on the "kv_last_request_id" field.
func KvLastRequestIDNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldKvLastRequestID, vs...))
}

// KvLastRequestIDGT applies the GT predicate on the "kv_last_request_id" field.
func KvLastRequestIDGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldKvLastRequestID, v))
}

// KvLastRequestIDGTE applies the GTE predicate on the "kv_last_request_id" field.
func KvLastRequestIDGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldKvLastRequestID, v))
}

// KvLastRequestIDLT applies the LT predicate on the "kv_last_request_id" field.
func KvLastRequestIDLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldKvLastRequestID, v))
}

// KvLastRequestIDLTE applies the LTE predicate on the "kv_last_request_id" field.
func KvLastRequestIDLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldKvLastRequestID, v))
}

// KvLastRequestIDContains applies the Contains predicate on the "kv_last_request_id" field.
func KvLastRequestIDContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldKvLastRequestID, v))
}

// KvLastRequestIDHasPrefix applies the HasPrefix predicate on the "kv_last_request_id" field.
func KvLastRequestIDHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldKvLastRequestID, v))
}

// KvLastRequestIDHasSuffix applies the HasSuffix predicate on the "kv_last_request_id" field.
func KvLastRequestIDHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldKvLastRequestID, v))
}

// KvLastRequestIDIsNil applies the IsNil predicate on the "kv_last_request_id" field.
func KvLastRequestIDIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldKvLastRequestID))
}

// KvLastRequestIDNotNil applies the NotNil predicate on the "kv_last_request_id" field.
func KvLastRequestIDNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldKvLastRequestID))
}

// KvLastRequestIDEqualFold applies the EqualFold predicate on the "kv_last_request_id" field.
func KvLastRequestIDEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldKvLastRequestID, v))
}

// KvLastRequestIDContainsFold applies the ContainsFold predicate on the "kv_last_request_id" field.
func KvLastRequestIDContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldKvLastRequestID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldContainsFold(FieldCreatedBy, v))
}

// KvLastSyncedAtEQ applies the EQ predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldKvLastSyncedAt, v))
}

// KvLastSyncedAtNEQ applies the NEQ predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtNEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldKvLastSyncedAt, v))
}

// KvLastSyncedAtIn applies the In predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldKvLastSyncedAt, vs...))
}

// KvLastSyncedAtNotIn applies the NotIn predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtNotIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldKvLastSyncedAt, vs...))
}

// KvLastSyncedAtGT applies the GT predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtGT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldKvLastSyncedAt, v))
}

// KvLastSyncedAtGTE applies the GTE predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtGTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldKvLastSyncedAt, v))
}

// KvLastSyncedAtLT applies the LT predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtLT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldKvLastSyncedAt, v))
}

// KvLastSyncedAtLTE applies the LTE predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtLTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldKvLastSyncedAt, v))
}

// KvLastSyncedAtIsNil applies the IsNil predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldKvLastSyncedAt))
}

// KvLastSyncedAtNotNil applies the NotNil predicate on the "kv_last_synced_at" field.
func KvLastSyncedAtNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldKvLastSyncedAt))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldVerifiedAt))
}

// PinsLoadedAtEQ applies the EQ predicate on the "pins_loaded_at" field.
func PinsLoadedAtEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldPinsLoadedAt, v))
}

// PinsLoadedAtNEQ applies the NEQ predicate on the "pins_loaded_at" field.
func PinsLoadedAtNEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldPinsLoadedAt, v))
}

// PinsLoadedAtIn applies the In predicate on the "pins_loaded_at" field.
func PinsLoadedAtIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldPinsLoadedAt, vs...))
}

// PinsLoadedAtNotIn applies the NotIn predicate on the "pins_loaded_at" field.
func PinsLoadedAtNotIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldPinsLoadedAt, vs...))
}

// PinsLoadedAtGT applies the GT predicate on the "pins_loaded_at" field.
func PinsLoadedAtGT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldPinsLoadedAt, v))
}

// PinsLoadedAtGTE applies the GTE predicate on the "pins_loaded_at" field.
func PinsLoadedAtGTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldPinsLoadedAt, v))
}

// PinsLoadedAtLT applies the LT predicate on the "pins_loaded_at" field.
func PinsLoadedAtLT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldPinsLoadedAt, v))
}

// PinsLoadedAtLTE applies the LTE predicate on the "pins_loaded_at" field.
func PinsLoadedAtLTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldPinsLoadedAt, v))
}

// PinsLoadedAtIsNil applies the IsNil predicate on the "pins_loaded_at" field.
func PinsLoadedAtIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldPinsLoadedAt))
}

// PinsLoadedAtNotNil applies the NotNil predicate on the "pins_loaded_at" field.
func PinsLoadedAtNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldPinsLoadedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VoucherB2BOrder) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VoucherB2BOrder) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VoucherB2BOrder) predicate.VoucherB2BOrder {
	return predicate.VoucherB2BOrder(sql.NotPredicates(p))
}
